include(ExternalProject)

set(STRONGSWAN_SOURCES_ROOT ${CMAKE_CURRENT_LIST_DIR}/sources)

ExternalProject_Add(
    strongswan
    UPDATE_DISCONNECTED true
    CONFIGURE_HANDLED_BY_BUILD true
    PREFIX ${STRONGSWAN_SOURCES_ROOT}
    SOURCE_DIR ${STRONGSWAN_SOURCES_ROOT}
    BINARY_DIR ${STRONGSWAN_SOURCES_ROOT}
    INSTALL_DIR ${STRONGSWAN_SOURCES_ROOT}
    STAMP_DIR ${STRONGSWAN_SOURCES_ROOT}/stamp
    LOG_DIR ${STRONGSWAN_SOURCES_ROOT}/log
    TMP_DIR ${STRONGSWAN_SOURCES_ROOT}/tmp
    CONFIGURE_COMMAND ./autogen.sh
    COMMAND ./configure --disable-kernel-netlink
    BUILD_COMMAND make #dist
    INSTALL_COMMAND ""
)
