@startjson
{
   "containers : array": 
        {
            "container : string": "amnezia-wireguard",
            "wireguard : array": 
                {
                    "isThirdPartyConfig : bool": "depends on import source",
                    "last_config : string": "native wireguard config",
                    "port : string": "port number",
                    "transport_proto : string": "udp"
                }
        },
    "defaultContainer : string": "amnezia-wireguard",
    "description : string": "server name alias",
    "dns1 : string": "dns address",
    "dns2 : string": "dns address",
    "hostName : string": "server address",
    "version : number": "2",
    "lastConfigStorage : string": "storage address"
}
@endjson