if(NOT CLIENT_SWIFT_MODULE_NAME)
    set(CLIENT_SWIFT_MODULE_NAME "${CLIENT_APPLICATION_NAME}" CACHE STRING "Swift module name for Objective-C interop header")
endif()
if(NOT CLIENT_SWIFT_OBJC_HEADER_NAME)
    set(CLIENT_SWIFT_OBJC_HEADER_NAME "${CLIENT_SWIFT_MODULE_NAME}-Swift.h" CACHE STRING "Generated Swift Objective-C header name")
endif()
if(NOT CLIENT_NETWORK_EXTENSION_NAME)
    set(CLIENT_NETWORK_EXTENSION_NAME "${CLIENT_APPLICATION_NAME}NetworkExtension" CACHE STRING "Display name for Apple network extension targets")
endif()
if(NOT CLIENT_MACOS_ST_TARGET_NAME)
    set(CLIENT_MACOS_ST_TARGET_NAME "${CLIENT_APPLICATION_NAME}SplitTunnel" CACHE STRING "macOS app split-tunnel system extension target name")
endif()
if(NOT CLIENT_MACOS_ST_BUNDLE_SUFFIX)
    set(CLIENT_MACOS_ST_BUNDLE_SUFFIX "split-tunnel" CACHE STRING "Bundle id suffix for the macOS split-tunnel system extension")
endif()
if(NOT CLIENT_MACOS_ST_BUNDLE_VERSION)
    # Bump on every change to the extension, otherwise sysextd keeps the copy it
    # already installed instead of replacing it.
    set(CLIENT_MACOS_ST_BUNDLE_VERSION "4" CACHE STRING "CFBundleVersion of the macOS split-tunnel system extension")
endif()

if(NOT BUILD_OSX_APP_IDENTIFIER)
    set(BUILD_OSX_APP_IDENTIFIER org.amnezia.AmneziaVPN CACHE STRING "OSX Application identifier")
endif()
if(NOT CLIENT_MACOS_ST_BUNDLE_ID)
    set(CLIENT_MACOS_ST_BUNDLE_ID "${BUILD_OSX_APP_IDENTIFIER}.${CLIENT_MACOS_ST_BUNDLE_SUFFIX}" CACHE STRING "Bundle identifier for the macOS split-tunnel system extension")
endif()
if(NOT BUILD_IOS_APP_IDENTIFIER)
    set(BUILD_IOS_APP_IDENTIFIER org.amnezia.AmneziaVPN CACHE STRING "iOS Application identifier")
endif()
if(NOT BUILD_IOS_GROUP_IDENTIFIER)
    set(BUILD_IOS_GROUP_IDENTIFIER group.org.amnezia.AmneziaVPN CACHE STRING "iOS Group identifier")
endif()
if(NOT BUILD_VPN_DEVELOPMENT_TEAM)
    set(BUILD_VPN_DEVELOPMENT_TEAM X7UJ388FXK CACHE STRING "Amnezia VPN Development Team")
endif()
