[Interface]
Address = $WIREGUARD_CLIENT_ADDRESS
DNS = $PRIMARY_DNS, $SECONDARY_DNS
PrivateKey = $WIREGUARD_CLIENT_PRIVATE_KEY

[Peer]
PublicKey = $WIREGUARD_SERVER_PUBLIC_KEY
PresharedKey = $WIREGUARD_PSK
AllowedIPs = $WIREGUARD_ALLOWED_IPS
Endpoint = $WIREGUARD_ENDPOINT_HOST:$WIREGUARD_SERVER_PORT
PersistentKeepalive = 25
