#ifndef UILOGIC_H
#define UILOGIC_H

#include <QRegExpValidator>
#include <QQmlEngine>
#include <functional>
#include "3rd/QRCodeGenerator/QRCodeGenerator.h"

#include "protocols/vpnprotocol.h"

#include "settings.h"
#include "sites_model.h"
#include "serversmodel.h"

class VpnConnection;

namespace PageEnumNS
{
Q_NAMESPACE
enum Page {Start = 0, NewServer, NewServerProtocols, Vpn,
           Wizard, WizardLow, WizardMedium, WizardHigh, WizardVpnMode, ServerConfiguring,
           GeneralSettings, AppSettings, NetworkSettings, ServerSettings,
           ServerVpnProtocols, ServersList, ShareConnection,  Sites,
           OpenVpnSettings, ShadowSocksSettings, CloakSettings};
Q_ENUM_NS(Page)
}

class UiLogic : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool frameWireguardSettingsVisible READ getFrameWireguardSettingsVisible WRITE setFrameWireguardSettingsVisible NOTIFY frameWireguardSettingsVisibleChanged)
    Q_PROPERTY(bool frameFireguardVisible READ getFrameFireguardVisible WRITE setFrameFireguardVisible NOTIFY frameFireguardVisibleChanged)
    Q_PROPERTY(bool frameNewServerSettingsParentWireguardVisible READ getFrameNewServerSettingsParentWireguardVisible WRITE setFrameNewServerSettingsParentWireguardVisible NOTIFY frameNewServerSettingsParentWireguardVisibleChanged)
    Q_PROPERTY(bool radioButtonSetupWizardMediumChecked READ getRadioButtonSetupWizardMediumChecked WRITE setRadioButtonSetupWizardMediumChecked NOTIFY radioButtonSetupWizardMediumCheckedChanged)
    Q_PROPERTY(QString lineEditSetupWizardHighWebsiteMaskingText READ getLineEditSetupWizardHighWebsiteMaskingText WRITE setLineEditSetupWizardHighWebsiteMaskingText NOTIFY lineEditSetupWizardHighWebsiteMaskingTextChanged)
    Q_PROPERTY(double progressBarNewServerConfiguringValue READ getProgressBarNewServerConfiguringValue WRITE setProgressBarNewServerConfiguringValue NOTIFY progressBarNewServerConfiguringValueChanged)
    Q_PROPERTY(bool pushButtonNewServerSettingsCloakChecked READ getPushButtonNewServerSettingsCloakChecked WRITE setPushButtonNewServerSettingsCloakChecked NOTIFY pushButtonNewServerSettingsCloakCheckedChanged)
    Q_PROPERTY(bool pushButtonNewServerSettingsSsChecked READ getPushButtonNewServerSettingsSsChecked WRITE setPushButtonNewServerSettingsSsChecked NOTIFY pushButtonNewServerSettingsSsCheckedChanged)
    Q_PROPERTY(bool pushButtonNewServerSettingsOpenvpnChecked READ getPushButtonNewServerSettingsOpenvpnChecked WRITE setPushButtonNewServerSettingsOpenvpnChecked NOTIFY pushButtonNewServerSettingsOpenvpnCheckedChanged)
    Q_PROPERTY(QString lineEditNewServerCloakPortText READ getLineEditNewServerCloakPortText WRITE setLineEditNewServerCloakPortText NOTIFY lineEditNewServerCloakPortTextChanged)
    Q_PROPERTY(QString lineEditNewServerCloakSiteText READ getLineEditNewServerCloakSiteText WRITE setLineEditNewServerCloakSiteText NOTIFY lineEditNewServerCloakSiteTextChanged)
    Q_PROPERTY(QString lineEditNewServerSsPortText READ getLineEditNewServerSsPortText WRITE setLineEditNewServerSsPortText NOTIFY lineEditNewServerSsPortTextChanged)
    Q_PROPERTY(QString comboBoxNewServerSsCipherText READ getComboBoxNewServerSsCipherText WRITE setComboBoxNewServerSsCipherText NOTIFY comboBoxNewServerSsCipherTextChanged)
    Q_PROPERTY(QString lineEditNewServerOpenvpnPortText READ getlineEditNewServerOpenvpnPortText WRITE setLineEditNewServerOpenvpnPortText NOTIFY lineEditNewServerOpenvpnPortTextChanged)
    Q_PROPERTY(QString comboBoxNewServerOpenvpnProtoText READ getComboBoxNewServerOpenvpnProtoText WRITE setComboBoxNewServerOpenvpnProtoText NOTIFY comboBoxNewServerOpenvpnProtoTextChanged)
    Q_PROPERTY(bool pushButtonNewServerConnectKeyChecked READ getPushButtonNewServerConnectKeyChecked WRITE setPushButtonNewServerConnectKeyChecked NOTIFY pushButtonNewServerConnectKeyCheckedChanged)
    Q_PROPERTY(QString lineEditStartExistingCodeText READ getLineEditStartExistingCodeText WRITE setLineEditStartExistingCodeText NOTIFY lineEditStartExistingCodeTextChanged)
    Q_PROPERTY(QString textEditNewServerSshKeyText READ getTextEditNewServerSshKeyText WRITE setTextEditNewServerSshKeyText NOTIFY textEditNewServerSshKeyTextChanged)
    Q_PROPERTY(QString lineEditNewServerIpText READ getLineEditNewServerIpText WRITE setLineEditNewServerIpText NOTIFY lineEditNewServerIpTextChanged)
    Q_PROPERTY(QString lineEditNewServerPasswordText READ getLineEditNewServerPasswordText WRITE setLineEditNewServerPasswordText NOTIFY lineEditNewServerPasswordTextChanged)
    Q_PROPERTY(QString lineEditNewServerLoginText READ getLineEditNewServerLoginText WRITE setLineEditNewServerLoginText NOTIFY lineEditNewServerLoginTextChanged)
    Q_PROPERTY(bool labelNewServerWaitInfoVisible READ getLabelNewServerWaitInfoVisible WRITE setLabelNewServerWaitInfoVisible NOTIFY labelNewServerWaitInfoVisibleChanged)
    Q_PROPERTY(QString labelNewServerWaitInfoText READ getLabelNewServerWaitInfoText WRITE setLabelNewServerWaitInfoText NOTIFY labelNewServerWaitInfoTextChanged)
    Q_PROPERTY(double progressBarNewServerConnectionMinimum READ getProgressBarNewServerConnectionMinimum WRITE setProgressBarNewServerConnectionMinimum NOTIFY progressBarNewServerConnectionMinimumChanged)
    Q_PROPERTY(double progressBarNewServerConnectionMaximum READ getProgressBarNewServerConnectionMaximum WRITE setProgressBarNewServerConnectionMaximum NOTIFY progressBarNewServerConnectionMaximumChanged)
    Q_PROPERTY(bool pushButtonBackFromStartVisible READ getPushButtonBackFromStartVisible WRITE setPushButtonBackFromStartVisible NOTIFY pushButtonBackFromStartVisibleChanged)
    Q_PROPERTY(bool pushButtonNewServerConnectVisible READ getPushButtonNewServerConnectVisible WRITE setPushButtonNewServerConnectVisible NOTIFY pushButtonNewServerConnectVisibleChanged)
    Q_PROPERTY(bool radioButtonVpnModeAllSitesChecked READ getRadioButtonVpnModeAllSitesChecked WRITE setRadioButtonVpnModeAllSitesChecked NOTIFY radioButtonVpnModeAllSitesCheckedChanged)
    Q_PROPERTY(bool radioButtonVpnModeForwardSitesChecked READ getRadioButtonVpnModeForwardSitesChecked WRITE setRadioButtonVpnModeForwardSitesChecked NOTIFY radioButtonVpnModeForwardSitesCheckedChanged)
    Q_PROPERTY(bool radioButtonVpnModeExceptSitesChecked READ getRadioButtonVpnModeExceptSitesChecked WRITE setRadioButtonVpnModeExceptSitesChecked NOTIFY radioButtonVpnModeExceptSitesCheckedChanged)
    Q_PROPERTY(bool pushButtonVpnAddSiteEnabled READ getPushButtonVpnAddSiteEnabled WRITE setPushButtonVpnAddSiteEnabled NOTIFY pushButtonVpnAddSiteEnabledChanged)
    Q_PROPERTY(bool checkBoxAppSettingsAutostartChecked READ getCheckBoxAppSettingsAutostartChecked WRITE setCheckBoxAppSettingsAutostartChecked NOTIFY checkBoxAppSettingsAutostartCheckedChanged)
    Q_PROPERTY(bool checkBoxAppSettingsAutoconnectChecked READ getCheckBoxAppSettingsAutoconnectChecked WRITE setCheckBoxAppSettingsAutoconnectChecked NOTIFY checkBoxAppSettingsAutoconnectCheckedChanged)
    Q_PROPERTY(bool checkBoxAppSettingsStartMinimizedChecked READ getCheckBoxAppSettingsStartMinimizedChecked WRITE setCheckBoxAppSettingsStartMinimizedChecked NOTIFY checkBoxAppSettingsStartMinimizedCheckedChanged)
    Q_PROPERTY(QString lineEditNetworkSettingsDns1Text READ getLineEditNetworkSettingsDns1Text WRITE setLineEditNetworkSettingsDns1Text NOTIFY lineEditNetworkSettingsDns1TextChanged)
    Q_PROPERTY(QString lineEditNetworkSettingsDns2Text READ getLineEditNetworkSettingsDns2Text WRITE setLineEditNetworkSettingsDns2Text NOTIFY lineEditNetworkSettingsDns2TextChanged)
    Q_PROPERTY(QString labelAppSettingsVersionText READ getLabelAppSettingsVersionText WRITE setLabelAppSettingsVersionText NOTIFY labelAppSettingsVersionTextChanged)
    Q_PROPERTY(bool pushButtonGeneralSettingsShareConnectionEnable READ getPushButtonGeneralSettingsShareConnectionEnable WRITE setPushButtonGeneralSettingsShareConnectionEnable NOTIFY pushButtonGeneralSettingsShareConnectionEnableChanged)
    Q_PROPERTY(bool labelServerSettingsWaitInfoVisible READ getLabelServerSettingsWaitInfoVisible WRITE setLabelServerSettingsWaitInfoVisible NOTIFY labelServerSettingsWaitInfoVisibleChanged)
    Q_PROPERTY(QString labelServerSettingsWaitInfoText READ getLabelServerSettingsWaitInfoText WRITE setLabelServerSettingsWaitInfoText NOTIFY labelServerSettingsWaitInfoTextChanged)
    Q_PROPERTY(bool pushButtonServerSettingsClearVisible READ getPushButtonServerSettingsClearVisible WRITE setPushButtonServerSettingsClearVisible NOTIFY pushButtonServerSettingsClearVisibleChanged)
    Q_PROPERTY(bool pushButtonServerSettingsClearClientCacheVisible READ getPushButtonServerSettingsClearClientCacheVisible WRITE setPushButtonServerSettingsClearClientCacheVisible NOTIFY pushButtonServerSettingsClearClientCacheVisibleChanged)
    Q_PROPERTY(bool pushButtonServerSettingsShareFullVisible READ getPushButtonServerSettingsShareFullVisible WRITE setPushButtonServerSettingsShareFullVisible NOTIFY pushButtonServerSettingsShareFullVisibleChanged)
    Q_PROPERTY(QString labelServerSettingsServerText READ getLabelServerSettingsServerText WRITE setLabelServerSettingsServerText NOTIFY labelServerSettingsServerTextChanged)
    Q_PROPERTY(QString lineEditServerSettingsDescriptionText READ getLineEditServerSettingsDescriptionText WRITE setLineEditServerSettingsDescriptionText NOTIFY lineEditServerSettingsDescriptionTextChanged)
    Q_PROPERTY(QString labelServerSettingsCurrentVpnProtocolText READ getLabelServerSettingsCurrentVpnProtocolText WRITE setLabelServerSettingsCurrentVpnProtocolText NOTIFY labelServerSettingsCurrentVpnProtocolTextChanged)
    Q_PROPERTY(int currentPageValue READ getCurrentPageValue WRITE setCurrentPageValue NOTIFY currentPageValueChanged)
    Q_PROPERTY(QString trayIconUrl READ getTrayIconUrl WRITE setTrayIconUrl NOTIFY trayIconUrlChanged)
    Q_PROPERTY(bool trayActionDisconnectEnabled READ getTrayActionDisconnectEnabled WRITE setTrayActionDisconnectEnabled NOTIFY trayActionDisconnectEnabledChanged)
    Q_PROPERTY(bool trayActionConnectEnabled READ getTrayActionConnectEnabled WRITE setTrayActionConnectEnabled NOTIFY trayActionConnectEnabledChanged)
    Q_PROPERTY(bool checkBoxNewServerCloakChecked READ getCheckBoxNewServerCloakChecked WRITE setCheckBoxNewServerCloakChecked NOTIFY checkBoxNewServerCloakCheckedChanged)
    Q_PROPERTY(bool checkBoxNewServerSsChecked READ getCheckBoxNewServerSsChecked WRITE setCheckBoxNewServerSsChecked NOTIFY checkBoxNewServerSsCheckedChanged)
    Q_PROPERTY(bool checkBoxNewServerOpenvpnChecked READ getCheckBoxNewServerOpenvpnChecked WRITE setCheckBoxNewServerOpenvpnChecked NOTIFY checkBoxNewServerOpenvpnCheckedChanged)
    Q_PROPERTY(QString comboBoxProtoCloakCipherText READ getComboBoxProtoCloakCipherText WRITE setComboBoxProtoCloakCipherText NOTIFY comboBoxProtoCloakCipherTextChanged)
    Q_PROPERTY(QString lineEditProtoCloakSiteText READ getLineEditProtoCloakSiteText WRITE setLineEditProtoCloakSiteText NOTIFY lineEditProtoCloakSiteTextChanged)
    Q_PROPERTY(QString lineEditProtoCloakPortText READ getLineEditProtoCloakPortText WRITE setLineEditProtoCloakPortText NOTIFY lineEditProtoCloakPortTextChanged)
    Q_PROPERTY(QString comboBoxProtoShadowsocksCipherText READ getComboBoxProtoShadowsocksCipherText WRITE setComboBoxProtoShadowsocksCipherText NOTIFY comboBoxProtoShadowsocksCipherTextChanged)
    Q_PROPERTY(QString lineEditProtoShadowsocksPortText READ getLineEditProtoShadowsocksPortText WRITE setLineEditProtoShadowsocksPortText NOTIFY lineEditProtoShadowsocksPortTextChanged)
    Q_PROPERTY(QString lineEditProtoOpenvpnSubnetText READ getLineEditProtoOpenvpnSubnetText WRITE setLineEditProtoOpenvpnSubnetText NOTIFY lineEditProtoOpenvpnSubnetTextChanged)
    Q_PROPERTY(bool radioButtonProtoOpenvpnUdpChecked READ getRadioButtonProtoOpenvpnUdpChecked WRITE setRadioButtonProtoOpenvpnUdpChecked NOTIFY radioButtonProtoOpenvpnUdpCheckedChanged)
    Q_PROPERTY(bool checkBoxProtoOpenvpnAutoEncryptionChecked READ getCheckBoxProtoOpenvpnAutoEncryptionChecked WRITE setCheckBoxProtoOpenvpnAutoEncryptionChecked NOTIFY checkBoxProtoOpenvpnAutoEncryptionCheckedChanged)
    Q_PROPERTY(QString comboBoxProtoOpenvpnCipherText READ getComboBoxProtoOpenvpnCipherText WRITE setComboBoxProtoOpenvpnCipherText NOTIFY comboBoxProtoOpenvpnCipherTextChanged)
    Q_PROPERTY(QString comboBoxProtoOpenvpnHashText READ getComboBoxProtoOpenvpnHashText WRITE setComboBoxProtoOpenvpnHashText NOTIFY comboBoxProtoOpenvpnHashTextChanged)
    Q_PROPERTY(bool checkBoxProtoOpenvpnBlockDnsChecked READ getCheckBoxProtoOpenvpnBlockDnsChecked WRITE setCheckBoxProtoOpenvpnBlockDnsChecked NOTIFY checkBoxProtoOpenvpnBlockDnsCheckedChanged)
    Q_PROPERTY(QString lineEditProtoOpenvpnPortText READ getLineEditProtoOpenvpnPortText WRITE setLineEditProtoOpenvpnPortText NOTIFY lineEditProtoOpenvpnPortTextChanged)
    Q_PROPERTY(bool checkBoxProtoOpenvpnTlsAuthChecked READ getCheckBoxProtoOpenvpnTlsAuthChecked WRITE setCheckBoxProtoOpenvpnTlsAuthChecked NOTIFY checkBoxProtoOpenvpnTlsAuthCheckedChanged)
    Q_PROPERTY(bool radioButtonSetupWizardHighChecked READ getRadioButtonSetupWizardHighChecked WRITE setRadioButtonSetupWizardHighChecked NOTIFY radioButtonSetupWizardHighCheckedChanged)
    Q_PROPERTY(bool radioButtonSetupWizardLowChecked READ getRadioButtonSetupWizardLowChecked WRITE setRadioButtonSetupWizardLowChecked NOTIFY radioButtonSetupWizardLowCheckedChanged)
    Q_PROPERTY(bool checkBoxSetupWizardVpnModeChecked READ getCheckBoxSetupWizardVpnModeChecked WRITE setCheckBoxSetupWizardVpnModeChecked NOTIFY checkBoxSetupWizardVpnModeCheckedChanged)
    Q_PROPERTY(QString ipAddressValidatorRegex READ getIpAddressValidatorRegex CONSTANT)
    Q_PROPERTY(bool pushButtonConnectChecked READ getPushButtonConnectChecked WRITE setPushButtonConnectChecked NOTIFY pushButtonConnectCheckedChanged)
    Q_PROPERTY(QString labelSitesAddCustomText READ getLabelSitesAddCustomText WRITE setLabelSitesAddCustomText NOTIFY labelSitesAddCustomTextChanged)
    Q_PROPERTY(QObject* tableViewSitesModel READ getTableViewSitesModel NOTIFY tableViewSitesModelChanged)
    Q_PROPERTY(QString lineEditSitesAddCustomText READ getLineEditSitesAddCustomText WRITE setLineEditSitesAddCustomText NOTIFY lineEditSitesAddCustomTextChanged)
    Q_PROPERTY(bool widgetProtoCloakEnabled READ getWidgetProtoCloakEnabled WRITE setWidgetProtoCloakEnabled NOTIFY widgetProtoCloakEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoCloakSaveVisible READ getPushButtonProtoCloakSaveVisible WRITE setPushButtonProtoCloakSaveVisible NOTIFY pushButtonProtoCloakSaveVisibleChanged)
    Q_PROPERTY(bool progressBarProtoCloakResetVisible READ getProgressBarProtoCloakResetVisible WRITE setProgressBarProtoCloakResetVisible NOTIFY progressBarProtoCloakResetVisibleChanged)
    Q_PROPERTY(bool lineEditProtoCloakPortEnabled READ getLineEditProtoCloakPortEnabled WRITE setLineEditProtoCloakPortEnabled NOTIFY lineEditProtoCloakPortEnabledChanged)
    Q_PROPERTY(bool widgetProtoSsEnabled READ getWidgetProtoSsEnabled WRITE setWidgetProtoSsEnabled NOTIFY widgetProtoSsEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoShadowsocksSaveVisible READ getPushButtonProtoShadowsocksSaveVisible WRITE setPushButtonProtoShadowsocksSaveVisible NOTIFY pushButtonProtoShadowsocksSaveVisibleChanged)
    Q_PROPERTY(bool progressBarProtoShadowsocksResetVisible READ getProgressBarProtoShadowsocksResetVisible WRITE setProgressBarProtoShadowsocksResetVisible NOTIFY progressBarProtoShadowsocksResetVisibleChanged)
    Q_PROPERTY(bool lineEditProtoShadowsocksPortEnabled READ getLineEditProtoShadowsocksPortEnabled WRITE setLineEditProtoShadowsocksPortEnabled NOTIFY lineEditProtoShadowsocksPortEnabledChanged)
    Q_PROPERTY(bool widgetProtoOpenvpnEnabled READ getWidgetProtoOpenvpnEnabled WRITE setWidgetProtoOpenvpnEnabled NOTIFY widgetProtoOpenvpnEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoOpenvpnSaveVisible READ getPushButtonProtoOpenvpnSaveVisible WRITE setPushButtonProtoOpenvpnSaveVisible NOTIFY pushButtonProtoOpenvpnSaveVisibleChanged)
    Q_PROPERTY(bool progressBarProtoOpenvpnResetVisible READ getProgressBarProtoOpenvpnResetVisible WRITE setProgressBarProtoOpenvpnResetVisible NOTIFY progressBarProtoOpenvpnResetVisibleChanged)
    Q_PROPERTY(bool radioButtonProtoOpenvpnUdpEnabled READ getRadioButtonProtoOpenvpnUdpEnabled WRITE setRadioButtonProtoOpenvpnUdpEnabled NOTIFY radioButtonProtoOpenvpnUdpEnabledChanged)
    Q_PROPERTY(bool radioButtonProtoOpenvpnTcpEnabled READ getRadioButtonProtoOpenvpnTcpEnabled WRITE setRadioButtonProtoOpenvpnTcpEnabled NOTIFY radioButtonProtoOpenvpnTcpEnabledChanged)
    Q_PROPERTY(bool radioButtonProtoOpenvpnTcpChecked READ getRadioButtonProtoOpenvpnTcpChecked WRITE setRadioButtonProtoOpenvpnTcpChecked NOTIFY radioButtonProtoOpenvpnTcpCheckedChanged)
    Q_PROPERTY(bool lineEditProtoOpenvpnPortEnabled READ getLineEditProtoOpenvpnPortEnabled WRITE setLineEditProtoOpenvpnPortEnabled NOTIFY lineEditProtoOpenvpnPortEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoOpenvpnContInstallChecked READ getPushButtonProtoOpenvpnContInstallChecked WRITE setPushButtonProtoOpenvpnContInstallChecked NOTIFY pushButtonProtoOpenvpnContInstallCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoSsOpenvpnContInstallChecked READ getPushButtonProtoSsOpenvpnContInstallChecked WRITE setPushButtonProtoSsOpenvpnContInstallChecked NOTIFY pushButtonProtoSsOpenvpnContInstallCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoCloakOpenvpnContInstallChecked READ getPushButtonProtoCloakOpenvpnContInstallChecked WRITE setPushButtonProtoCloakOpenvpnContInstallChecked NOTIFY pushButtonProtoCloakOpenvpnContInstallCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoWireguardContInstallChecked READ getPushButtonProtoWireguardContInstallChecked WRITE setPushButtonProtoWireguardContInstallChecked NOTIFY pushButtonProtoWireguardContInstallCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoOpenvpnContInstallEnabled READ getPushButtonProtoOpenvpnContInstallEnabled WRITE setPushButtonProtoOpenvpnContInstallEnabled NOTIFY pushButtonProtoOpenvpnContInstallEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoSsOpenvpnContInstallEnabled READ getPushButtonProtoSsOpenvpnContInstallEnabled WRITE setPushButtonProtoSsOpenvpnContInstallEnabled NOTIFY pushButtonProtoSsOpenvpnContInstallEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoCloakOpenvpnContInstallEnabled READ getPushButtonProtoCloakOpenvpnContInstallEnabled WRITE setPushButtonProtoCloakOpenvpnContInstallEnabled NOTIFY pushButtonProtoCloakOpenvpnContInstallEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoWireguardContInstallEnabled READ getPushButtonProtoWireguardContInstallEnabled WRITE setPushButtonProtoWireguardContInstallEnabled NOTIFY pushButtonProtoWireguardContInstallEnabledChanged)
    Q_PROPERTY(bool pushButtonProtoOpenvpnContDefaultChecked READ getPushButtonProtoOpenvpnContDefaultChecked WRITE setPushButtonProtoOpenvpnContDefaultChecked NOTIFY pushButtonProtoOpenvpnContDefaultCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoSsOpenvpnContDefaultChecked READ getPushButtonProtoSsOpenvpnContDefaultChecked WRITE setPushButtonProtoSsOpenvpnContDefaultChecked NOTIFY pushButtonProtoSsOpenvpnContDefaultCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoCloakOpenvpnContDefaultChecked READ getPushButtonProtoCloakOpenvpnContDefaultChecked WRITE setPushButtonProtoCloakOpenvpnContDefaultChecked NOTIFY pushButtonProtoCloakOpenvpnContDefaultCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoWireguardContDefaultChecked READ getPushButtonProtoWireguardContDefaultChecked WRITE setPushButtonProtoWireguardContDefaultChecked NOTIFY pushButtonProtoWireguardContDefaultCheckedChanged)
    Q_PROPERTY(bool pushButtonProtoOpenvpnContDefaultVisible READ getPushButtonProtoOpenvpnContDefaultVisible WRITE setPushButtonProtoOpenvpnContDefaultVisible NOTIFY pushButtonProtoOpenvpnContDefaultVisibleChanged)
    Q_PROPERTY(bool pushButtonProtoSsOpenvpnContDefaultVisible READ getPushButtonProtoSsOpenvpnContDefaultVisible WRITE setPushButtonProtoSsOpenvpnContDefaultVisible NOTIFY pushButtonProtoSsOpenvpnContDefaultVisibleChanged)
    Q_PROPERTY(bool pushButtonProtoCloakOpenvpnContDefaultVisible READ getPushButtonProtoCloakOpenvpnContDefaultVisible WRITE setPushButtonProtoCloakOpenvpnContDefaultVisible NOTIFY pushButtonProtoCloakOpenvpnContDefaultVisibleChanged)
    Q_PROPERTY(bool pushButtonProtoWireguardContDefaultVisible READ getPushButtonProtoWireguardContDefaultVisible WRITE setPushButtonProtoWireguardContDefaultVisible NOTIFY pushButtonProtoWireguardContDefaultVisibleChanged)
    Q_PROPERTY(bool pushButtonProtoOpenvpnContShareVisible READ getPushButtonProtoOpenvpnContShareVisible WRITE setPushButtonProtoOpenvpnContShareVisible NOTIFY pushButtonProtoOpenvpnContShareVisibleChanged)
    Q_PROPERTY(bool pushButtonProtoSsOpenvpnContShareVisible READ getPushButtonProtoSsOpenvpnContShareVisible WRITE setPushButtonProtoSsOpenvpnContShareVisible NOTIFY pushButtonProtoSsOpenvpnContShareVisibleChanged)
    Q_PROPERTY(bool pushButtonProtoCloakOpenvpnContShareVisible READ getPushButtonProtoCloakOpenvpnContShareVisible WRITE setPushButtonProtoCloakOpenvpnContShareVisible NOTIFY pushButtonProtoCloakOpenvpnContShareVisibleChanged)
    Q_PROPERTY(bool pushButtonProtoWireguardContShareVisible READ getPushButtonProtoWireguardContShareVisible WRITE setPushButtonProtoWireguardContShareVisible NOTIFY pushButtonProtoWireguardContShareVisibleChanged)
    Q_PROPERTY(bool frameOpenvpnSettingsVisible READ getFrameOpenvpnSettingsVisible WRITE setFrameOpenvpnSettingsVisible NOTIFY frameOpenvpnSettingsVisibleChanged)
    Q_PROPERTY(bool frameOpenvpnSsSettingsVisible READ getFrameOpenvpnSsSettingsVisible WRITE setFrameOpenvpnSsSettingsVisible NOTIFY frameOpenvpnSsSettingsVisibleChanged)
    Q_PROPERTY(bool frameOpenvpnSsCloakSettingsVisible READ getFrameOpenvpnSsCloakSettingsVisible WRITE setFrameOpenvpnSsCloakSettingsVisible NOTIFY frameOpenvpnSsCloakSettingsVisibleChanged)
    Q_PROPERTY(bool progressBarProtocolsContainerReinstallVisible READ getProgressBarProtocolsContainerReinstallVisible WRITE setProgressBarProtocolsContainerReinstallVisible NOTIFY progressBarProtocolsContainerReinstallVisibleChanged)
    Q_PROPERTY(QString labelSpeedReceivedText READ getLabelSpeedReceivedText WRITE setLabelSpeedReceivedText NOTIFY labelSpeedReceivedTextChanged)
    Q_PROPERTY(QString labelSpeedSentText READ getLabelSpeedSentText WRITE setLabelSpeedSentText NOTIFY labelSpeedSentTextChanged)
    Q_PROPERTY(QString labelStateText READ getLabelStateText WRITE setLabelStateText NOTIFY labelStateTextChanged)
    Q_PROPERTY(bool pushButtonConnectEnabled READ getPushButtonConnectEnabled WRITE setPushButtonConnectEnabled NOTIFY pushButtonConnectEnabledChanged)
    Q_PROPERTY(bool widgetVpnModeEnabled READ getWidgetVpnModeEnabled WRITE setWidgetVpnModeEnabled NOTIFY widgetVpnModeEnabledChanged)
    Q_PROPERTY(QString labelErrorText READ getLabelErrorText WRITE setLabelErrorText NOTIFY labelErrorTextChanged)
    Q_PROPERTY(bool pushButtonNewServerConnectEnabled READ getPushButtonNewServerConnectEnabled WRITE setPushButtonNewServerConnectEnabled NOTIFY pushButtonNewServerConnectEnabledChanged)
    Q_PROPERTY(QString pushButtonNewServerConnectText READ getPushButtonNewServerConnectText WRITE setPushButtonNewServerConnectText NOTIFY pushButtonNewServerConnectTextChanged)
    Q_PROPERTY(QString dialogConnectErrorText READ getDialogConnectErrorText WRITE setDialogConnectErrorText NOTIFY dialogConnectErrorTextChanged)
    Q_PROPERTY(bool pageServerSettingsEnabled READ getPageServerSettingsEnabled WRITE setPageServerSettingsEnabled NOTIFY pageServerSettingsEnabledChanged)
    Q_PROPERTY(QString pushButtonServerSettingsClearText READ getPushButtonServerSettingsClearText WRITE setPushButtonServerSettingsClearText NOTIFY pushButtonServerSettingsClearTextChanged)
    Q_PROPERTY(bool pageShareAmneziaVisible READ getPageShareAmneziaVisible WRITE setPageShareAmneziaVisible NOTIFY pageShareAmneziaVisibleChanged)
    Q_PROPERTY(bool pageShareOpenvpnVisible READ getPageShareOpenvpnVisible WRITE setPageShareOpenvpnVisible NOTIFY pageShareOpenvpnVisibleChanged)
    Q_PROPERTY(bool pageShareShadowsocksVisible READ getPageShareShadowsocksVisible WRITE setPageShareShadowsocksVisible NOTIFY pageShareShadowsocksVisibleChanged)
    Q_PROPERTY(bool pageShareCloakVisible READ getPageShareCloakVisible WRITE setPageShareCloakVisible NOTIFY pageShareCloakVisibleChanged)
    Q_PROPERTY(bool pageShareFullAccessVisible READ getPageShareFullAccessVisible WRITE setPageShareFullAccessVisible NOTIFY pageShareFullAccessVisibleChanged)
    Q_PROPERTY(QString textEditShareOpenvpnCodeText READ getTextEditShareOpenvpnCodeText WRITE setTextEditShareOpenvpnCodeText NOTIFY textEditShareOpenvpnCodeTextChanged)
    Q_PROPERTY(bool pushButtonShareOpenvpnCopyEnabled READ getPushButtonShareOpenvpnCopyEnabled WRITE setPushButtonShareOpenvpnCopyEnabled NOTIFY pushButtonShareOpenvpnCopyEnabledChanged)
    Q_PROPERTY(bool pushButtonShareOpenvpnSaveEnabled READ getPushButtonShareOpenvpnSaveEnabled WRITE setPushButtonShareOpenvpnSaveEnabled NOTIFY pushButtonShareOpenvpnSaveEnabledChanged)
    Q_PROPERTY(int toolBoxShareConnectionCurrentIndex READ getToolBoxShareConnectionCurrentIndex WRITE setToolBoxShareConnectionCurrentIndex NOTIFY toolBoxShareConnectionCurrentIndexChanged)
    Q_PROPERTY(bool pushButtonShareSsCopyEnabled READ getPushButtonShareSsCopyEnabled WRITE setPushButtonShareSsCopyEnabled NOTIFY pushButtonShareSsCopyEnabledChanged)
    Q_PROPERTY(QString lineEditShareSsStringText READ getLineEditShareSsStringText WRITE setLineEditShareSsStringText NOTIFY lineEditShareSsStringTextChanged)
    Q_PROPERTY(QString labelShareSsQrCodeText READ getLabelShareSsQrCodeText WRITE setLabelShareSsQrCodeText NOTIFY labelShareSsQrCodeTextChanged)
    Q_PROPERTY(QString labelShareSsServerText READ getLabelShareSsServerText WRITE setLabelShareSsServerText NOTIFY labelShareSsServerTextChanged)
    Q_PROPERTY(QString labelShareSsPortText READ getLabelShareSsPortText WRITE setLabelShareSsPortText NOTIFY labelShareSsPortTextChanged)
    Q_PROPERTY(QString labelShareSsMethodText READ getLabelShareSsMethodText WRITE setLabelShareSsMethodText NOTIFY labelShareSsMethodTextChanged)
    Q_PROPERTY(QString labelShareSsPasswordText READ getLabelShareSsPasswordText WRITE setLabelShareSsPasswordText NOTIFY labelShareSsPasswordTextChanged)
    Q_PROPERTY(QString plainTextEditShareCloakText READ getPlainTextEditShareCloakText WRITE setPlainTextEditShareCloakText NOTIFY plainTextEditShareCloakTextChanged)
    Q_PROPERTY(bool pushButtonShareCloakCopyEnabled READ getPushButtonShareCloakCopyEnabled WRITE setPushButtonShareCloakCopyEnabled NOTIFY pushButtonShareCloakCopyEnabledChanged)
    Q_PROPERTY(QString textEditShareFullCodeText READ getTextEditShareFullCodeText WRITE setTextEditShareFullCodeText NOTIFY textEditShareFullCodeTextChanged)
    Q_PROPERTY(QString textEditShareAmneziaCodeText READ getTextEditShareAmneziaCodeText WRITE setTextEditShareAmneziaCodeText NOTIFY textEditShareAmneziaCodeTextChanged)
    Q_PROPERTY(QString pushButtonShareFullCopyText READ getPushButtonShareFullCopyText WRITE setPushButtonShareFullCopyText NOTIFY pushButtonShareFullCopyTextChanged)
    Q_PROPERTY(QString pushButtonShareAmneziaCopyText READ getPushButtonShareAmneziaCopyText WRITE setPushButtonShareAmneziaCopyText NOTIFY pushButtonShareAmneziaCopyTextChanged)
    Q_PROPERTY(QString pushButtonShareOpenvpnCopyText READ getPushButtonShareOpenvpnCopyText WRITE setPushButtonShareOpenvpnCopyText NOTIFY pushButtonShareOpenvpnCopyTextChanged)
    Q_PROPERTY(QString pushButtonShareSsCopyText READ getPushButtonShareSsCopyText WRITE setPushButtonShareSsCopyText NOTIFY pushButtonShareSsCopyTextChanged)
    Q_PROPERTY(QString pushButtonShareCloakCopyText READ getPushButtonShareCloakCopyText WRITE setPushButtonShareCloakCopyText NOTIFY pushButtonShareCloakCopyTextChanged)
    Q_PROPERTY(bool pushButtonShareAmneziaGenerateEnabled READ getPushButtonShareAmneziaGenerateEnabled WRITE setPushButtonShareAmneziaGenerateEnabled NOTIFY pushButtonShareAmneziaGenerateEnabledChanged)
    Q_PROPERTY(bool pushButtonShareAmneziaCopyEnabled READ getPushButtonShareAmneziaCopyEnabled WRITE setPushButtonShareAmneziaCopyEnabled NOTIFY pushButtonShareAmneziaCopyEnabledChanged)
    Q_PROPERTY(QString pushButtonShareAmneziaGenerateText READ getPushButtonShareAmneziaGenerateText WRITE setPushButtonShareAmneziaGenerateText NOTIFY pushButtonShareAmneziaGenerateTextChanged)
    Q_PROPERTY(bool pushButtonShareOpenvpnGenerateEnabled READ getPushButtonShareOpenvpnGenerateEnabled WRITE setPushButtonShareOpenvpnGenerateEnabled NOTIFY pushButtonShareOpenvpnGenerateEnabledChanged)
    Q_PROPERTY(QString pushButtonShareOpenvpnGenerateText READ getPushButtonShareOpenvpnGenerateText WRITE setPushButtonShareOpenvpnGenerateText NOTIFY pushButtonShareOpenvpnGenerateTextChanged)
    Q_PROPERTY(bool pageNewServerConfiguringEnabled READ getPageNewServerConfiguringEnabled WRITE setPageNewServerConfiguringEnabled NOTIFY pageNewServerConfiguringEnabledChanged)
    Q_PROPERTY(bool labelNewServerConfiguringWaitInfoVisible READ getLabelNewServerConfiguringWaitInfoVisible WRITE setLabelNewServerConfiguringWaitInfoVisible NOTIFY labelNewServerConfiguringWaitInfoVisibleChanged)
    Q_PROPERTY(QString labelNewServerConfiguringWaitInfoText READ getLabelNewServerConfiguringWaitInfoText WRITE setLabelNewServerConfiguringWaitInfoText NOTIFY labelNewServerConfiguringWaitInfoTextChanged)
    Q_PROPERTY(bool progressBarNewServerConfiguringVisible READ getProgressBarNewServerConfiguringVisible WRITE setProgressBarNewServerConfiguringVisible NOTIFY progressBarNewServerConfiguringVisibleChanged)
    Q_PROPERTY(int progressBarNewServerConfiguringMaximium READ getProgressBarNewServerConfiguringMaximium WRITE setProgressBarNewServerConfiguringMaximium NOTIFY progressBarNewServerConfiguringMaximiumChanged)
    Q_PROPERTY(bool progressBarNewServerConfiguringTextVisible READ getProgressBarNewServerConfiguringTextVisible WRITE setProgressBarNewServerConfiguringTextVisible NOTIFY progressBarNewServerConfiguringTextVisibleChanged)
    Q_PROPERTY(QString progressBarNewServerConfiguringText READ getProgressBarNewServerConfiguringText WRITE setProgressBarNewServerConfiguringText NOTIFY progressBarNewServerConfiguringTextChanged)
    Q_PROPERTY(bool pageServerProtocolsEnabled READ getPageServerProtocolsEnabled WRITE setPageServerProtocolsEnabled NOTIFY pageServerProtocolsEnabledChanged)
    Q_PROPERTY(int progressBarProtocolsContainerReinstallValue READ getProgressBarProtocolsContainerReinstallValue WRITE setProgressBarProtocolsContainerReinstallValue NOTIFY progressBarProtocolsContainerReinstallValueChanged)
    Q_PROPERTY(int progressBarProtocolsContainerReinstallMaximium READ getProgressBarProtocolsContainerReinstallMaximium WRITE setProgressBarProtocolsContainerReinstallMaximium NOTIFY progressBarProtocolsContainerReinstallMaximiumChanged)
    Q_PROPERTY(bool comboBoxProtoOpenvpnCipherEnabled READ getComboBoxProtoOpenvpnCipherEnabled WRITE setComboBoxProtoOpenvpnCipherEnabled NOTIFY comboBoxProtoOpenvpnCipherEnabledChanged)
    Q_PROPERTY(bool comboBoxProtoOpenvpnHashEnabled READ getComboBoxProtoOpenvpnHashEnabled WRITE setComboBoxProtoOpenvpnHashEnabled NOTIFY comboBoxProtoOpenvpnHashEnabledChanged)
    Q_PROPERTY(bool pageProtoOpenvpnEnabled READ getPageProtoOpenvpnEnabled WRITE setPageProtoOpenvpnEnabled NOTIFY pageProtoOpenvpnEnabledChanged)
    Q_PROPERTY(bool labelProtoOpenvpnInfoVisible READ getLabelProtoOpenvpnInfoVisible WRITE setLabelProtoOpenvpnInfoVisible NOTIFY labelProtoOpenvpnInfoVisibleChanged)
    Q_PROPERTY(QString labelProtoOpenvpnInfoText READ getLabelProtoOpenvpnInfoText WRITE setLabelProtoOpenvpnInfoText NOTIFY labelProtoOpenvpnInfoTextChanged)
    Q_PROPERTY(int progressBarProtoOpenvpnResetValue READ getProgressBarProtoOpenvpnResetValue WRITE setProgressBarProtoOpenvpnResetValue NOTIFY progressBarProtoOpenvpnResetValueChanged)
    Q_PROPERTY(int progressBarProtoOpenvpnResetMaximium READ getProgressBarProtoOpenvpnResetMaximium WRITE setProgressBarProtoOpenvpnResetMaximium NOTIFY progressBarProtoOpenvpnResetMaximiumChanged)
    Q_PROPERTY(bool pageProtoShadowsocksEnabled READ getPageProtoShadowsocksEnabled WRITE setPageProtoShadowsocksEnabled NOTIFY pageProtoShadowsocksEnabledChanged)
    Q_PROPERTY(bool labelProtoShadowsocksInfoVisible READ getLabelProtoShadowsocksInfoVisible WRITE setLabelProtoShadowsocksInfoVisible NOTIFY labelProtoShadowsocksInfoVisibleChanged)
    Q_PROPERTY(QString labelProtoShadowsocksInfoText READ getLabelProtoShadowsocksInfoText WRITE setLabelProtoShadowsocksInfoText NOTIFY labelProtoShadowsocksInfoTextChanged)
    Q_PROPERTY(int progressBarProtoShadowsocksResetValue READ getProgressBarProtoShadowsocksResetValue WRITE setProgressBarProtoShadowsocksResetValue NOTIFY progressBarProtoShadowsocksResetValueChanged)
    Q_PROPERTY(int progressBarProtoShadowsocksResetMaximium READ getProgressBarProtoShadowsocksResetMaximium WRITE setProgressBarProtoShadowsocksResetMaximium NOTIFY progressBarProtoShadowsocksResetMaximiumChanged)
    Q_PROPERTY(bool pageProtoCloakEnabled READ getPageProtoCloakEnabled WRITE setPageProtoCloakEnabled NOTIFY pageProtoCloakEnabledChanged)
    Q_PROPERTY(bool labelProtoCloakInfoVisible READ getLabelProtoCloakInfoVisible WRITE setLabelProtoCloakInfoVisible NOTIFY labelProtoCloakInfoVisibleChanged)
    Q_PROPERTY(QString labelProtoCloakInfoText READ getLabelProtoCloakInfoText WRITE setLabelProtoCloakInfoText NOTIFY labelProtoCloakInfoTextChanged)
    Q_PROPERTY(int progressBarProtoCloakResetValue READ getProgressBarProtoCloakResetValue WRITE setProgressBarProtoCloakResetValue NOTIFY progressBarProtoCloakResetValueChanged)
    Q_PROPERTY(int progressBarProtoCloakResetMaximium READ getProgressBarProtoCloakResetMaximium WRITE setProgressBarProtoCloakResetMaximium NOTIFY progressBarProtoCloakResetMaximiumChanged)
    Q_PROPERTY(QObject* serverListModel READ getServerListModel CONSTANT)
    Q_PROPERTY(QString pushButtonServerSettingsClearClientCacheText READ getPushButtonServerSettingsClearClientCacheText WRITE setPushButtonServerSettingsClearClientCacheText NOTIFY pushButtonServerSettingsClearClientCacheTextChanged)


public:
    explicit UiLogic(QObject *parent = nullptr);
    ~UiLogic();
    void showOnStartup();

    Q_INVOKABLE void initalizeUiLogic();
    static void declareQML() {
        qmlRegisterUncreatableMetaObject(
                    PageEnumNS::staticMetaObject,
                    "PageEnum",
                    1, 0,
                    "PageEnum",
                    "Error: only enums"
                    );
    }
    bool getFrameWireguardSettingsVisible() const;
    void setFrameWireguardSettingsVisible(bool frameWireguardSettingsVisible);
    bool getFrameFireguardVisible() const;
    void setFrameFireguardVisible(bool frameFireguardVisible);
    bool getFrameNewServerSettingsParentWireguardVisible() const;
    void setFrameNewServerSettingsParentWireguardVisible(bool frameNewServerSettingsParentWireguardVisible);
    bool getRadioButtonSetupWizardMediumChecked() const;
    void setRadioButtonSetupWizardMediumChecked(bool radioButtonSetupWizardMediumChecked);
    QString getLineEditSetupWizardHighWebsiteMaskingText() const;
    void setLineEditSetupWizardHighWebsiteMaskingText(const QString &lineEditSetupWizardHighWebsiteMaskingText);
    double getProgressBarNewServerConfiguringValue() const;
    void setProgressBarNewServerConfiguringValue(double progressBarNewServerConfiguringValue);
    bool getPushButtonNewServerSettingsCloakChecked() const;
    void setPushButtonNewServerSettingsCloakChecked(bool pushButtonNewServerSettingsCloakChecked);
    bool getPushButtonNewServerSettingsSsChecked() const;
    void setPushButtonNewServerSettingsSsChecked(bool pushButtonNewServerSettingsSsChecked);
    bool getPushButtonNewServerSettingsOpenvpnChecked() const;
    void setPushButtonNewServerSettingsOpenvpnChecked(bool pushButtonNewServerSettingsOpenvpnChecked);
    QString getLineEditNewServerCloakPortText() const;
    void setLineEditNewServerCloakPortText(const QString &lineEditNewServerCloakPortText);
    QString getLineEditNewServerCloakSiteText() const;
    void setLineEditNewServerCloakSiteText(const QString &lineEditNewServerCloakSiteText);
    QString getLineEditNewServerSsPortText() const;
    void setLineEditNewServerSsPortText(const QString &lineEditNewServerSsPortText);
    QString getComboBoxNewServerSsCipherText() const;
    void setComboBoxNewServerSsCipherText(const QString &comboBoxNewServerSsCipherText);
    QString getlineEditNewServerOpenvpnPortText() const;
    void setLineEditNewServerOpenvpnPortText(const QString &lineEditNewServerOpenvpnPortText);
    QString getComboBoxNewServerOpenvpnProtoText() const;
    void setComboBoxNewServerOpenvpnProtoText(const QString &comboBoxNewServerOpenvpnProtoText);
    QString getLineEditStartExistingCodeText() const;
    void setLineEditStartExistingCodeText(const QString &lineEditStartExistingCodeText);
    QString getTextEditNewServerSshKeyText() const;
    void setTextEditNewServerSshKeyText(const QString &textEditNewServerSshKeyText);
    QString getLineEditNewServerIpText() const;
    void setLineEditNewServerIpText(const QString &lineEditNewServerIpText);
    QString getLineEditNewServerPasswordText() const;
    void setLineEditNewServerPasswordText(const QString &lineEditNewServerPasswordText);
    QString getLineEditNewServerLoginText() const;
    void setLineEditNewServerLoginText(const QString &lineEditNewServerLoginText);
    bool getLabelNewServerWaitInfoVisible() const;
    void setLabelNewServerWaitInfoVisible(bool labelNewServerWaitInfoVisible);
    QString getLabelNewServerWaitInfoText() const;
    void setLabelNewServerWaitInfoText(const QString &labelNewServerWaitInfoText);
    double getProgressBarNewServerConnectionMinimum() const;
    void setProgressBarNewServerConnectionMinimum(double progressBarNewServerConnectionMinimum);
    double getProgressBarNewServerConnectionMaximum() const;
    void setProgressBarNewServerConnectionMaximum(double progressBarNewServerConnectionMaximum);
    bool getPushButtonBackFromStartVisible() const;
    void setPushButtonBackFromStartVisible(bool pushButtonBackFromStartVisible);
    bool getPushButtonNewServerConnectVisible() const;
    void setPushButtonNewServerConnectVisible(bool pushButtonNewServerConnectVisible);
    bool getPushButtonNewServerConnectKeyChecked() const;
    void setPushButtonNewServerConnectKeyChecked(bool pushButtonNewServerConnectKeyChecked);
    bool getRadioButtonVpnModeAllSitesChecked() const;
    void setRadioButtonVpnModeAllSitesChecked(bool radioButtonVpnModeAllSitesChecked);
    bool getRadioButtonVpnModeForwardSitesChecked() const;
    void setRadioButtonVpnModeForwardSitesChecked(bool radioButtonVpnModeForwardSitesChecked);
    bool getRadioButtonVpnModeExceptSitesChecked() const;
    void setRadioButtonVpnModeExceptSitesChecked(bool radioButtonVpnModeExceptSitesChecked);
    bool getPushButtonVpnAddSiteEnabled() const;
    void setPushButtonVpnAddSiteEnabled(bool pushButtonVpnAddSiteEnabled);
    bool getCheckBoxAppSettingsAutostartChecked() const;
    void setCheckBoxAppSettingsAutostartChecked(bool checkBoxAppSettingsAutostartChecked);
    bool getCheckBoxAppSettingsAutoconnectChecked() const;
    void setCheckBoxAppSettingsAutoconnectChecked(bool checkBoxAppSettingsAutoconnectChecked);
    bool getCheckBoxAppSettingsStartMinimizedChecked() const;
    void setCheckBoxAppSettingsStartMinimizedChecked(bool checkBoxAppSettingsStartMinimizedChecked);
    QString getLineEditNetworkSettingsDns1Text() const;
    void setLineEditNetworkSettingsDns1Text(const QString &lineEditNetworkSettingsDns1Text);
    QString getLineEditNetworkSettingsDns2Text() const;
    void setLineEditNetworkSettingsDns2Text(const QString &lineEditNetworkSettingsDns2Text);
    QString getLabelAppSettingsVersionText() const;
    void setLabelAppSettingsVersionText(const QString &labelAppSettingsVersionText);
    bool getPushButtonGeneralSettingsShareConnectionEnable() const;
    void setPushButtonGeneralSettingsShareConnectionEnable(bool pushButtonGeneralSettingsShareConnectionEnable);
    bool getLabelServerSettingsWaitInfoVisible() const;
    void setLabelServerSettingsWaitInfoVisible(bool labelServerSettingsWaitInfoVisible);
    QString getLabelServerSettingsWaitInfoText() const;
    void setLabelServerSettingsWaitInfoText(const QString &labelServerSettingsWaitInfoText);
    bool getPushButtonServerSettingsClearVisible() const;
    void setPushButtonServerSettingsClearVisible(bool pushButtonServerSettingsClearVisible);
    bool getPushButtonServerSettingsClearClientCacheVisible() const;
    void setPushButtonServerSettingsClearClientCacheVisible(bool pushButtonServerSettingsClearClientCacheVisible);
    bool getPushButtonServerSettingsShareFullVisible() const;
    void setPushButtonServerSettingsShareFullVisible(bool pushButtonServerSettingsShareFullVisible);
    QString getLabelServerSettingsServerText() const;
    void setLabelServerSettingsServerText(const QString &labelServerSettingsServerText);
    QString getLineEditServerSettingsDescriptionText() const;
    void setLineEditServerSettingsDescriptionText(const QString &lineEditServerSettingsDescriptionText);
    QString getLabelServerSettingsCurrentVpnProtocolText() const;
    void setLabelServerSettingsCurrentVpnProtocolText(const QString &labelServerSettingsCurrentVpnProtocolText);
    int getCurrentPageValue() const;
    void setCurrentPageValue(int currentPageValue);
    QString getTrayIconUrl() const;
    void setTrayIconUrl(const QString &trayIconUrl);
    bool getTrayActionDisconnectEnabled() const;
    void setTrayActionDisconnectEnabled(bool trayActionDisconnectEnabled);
    bool getTrayActionConnectEnabled() const;
    void setTrayActionConnectEnabled(bool trayActionConnectEnabled);
    bool getCheckBoxNewServerCloakChecked() const;
    void setCheckBoxNewServerCloakChecked(bool checkBoxNewServerCloakChecked);
    bool getCheckBoxNewServerSsChecked() const;
    void setCheckBoxNewServerSsChecked(bool checkBoxNewServerSsChecked);
    bool getCheckBoxNewServerOpenvpnChecked() const;
    void setCheckBoxNewServerOpenvpnChecked(bool checkBoxNewServerOpenvpnChecked);
    QString getComboBoxProtoCloakCipherText() const;
    void setComboBoxProtoCloakCipherText(const QString &comboBoxProtoCloakCipherText);
    QString getLineEditProtoCloakSiteText() const;
    void setLineEditProtoCloakSiteText(const QString &lineEditProtoCloakSiteText);
    QString getLineEditProtoCloakPortText() const;
    void setLineEditProtoCloakPortText(const QString &lineEditProtoCloakPortText);
    QString getComboBoxProtoShadowsocksCipherText() const;
    void setComboBoxProtoShadowsocksCipherText(const QString &comboBoxProtoShadowsocksCipherText);
    QString getLineEditProtoShadowsocksPortText() const;
    void setLineEditProtoShadowsocksPortText(const QString &lineEditProtoShadowsocksPortText);
    QString getLineEditProtoOpenvpnSubnetText() const;
    void setLineEditProtoOpenvpnSubnetText(const QString &lineEditProtoOpenvpnSubnetText);
    bool getRadioButtonProtoOpenvpnUdpChecked() const;
    void setRadioButtonProtoOpenvpnUdpChecked(bool radioButtonProtoOpenvpnUdpChecked);
    bool getCheckBoxProtoOpenvpnAutoEncryptionChecked() const;
    void setCheckBoxProtoOpenvpnAutoEncryptionChecked(bool checkBoxProtoOpenvpnAutoEncryptionChecked);
    QString getComboBoxProtoOpenvpnCipherText() const;
    void setComboBoxProtoOpenvpnCipherText(const QString &comboBoxProtoOpenvpnCipherText);
    QString getComboBoxProtoOpenvpnHashText() const;
    void setComboBoxProtoOpenvpnHashText(const QString &comboBoxProtoOpenvpnHashText);
    bool getCheckBoxProtoOpenvpnBlockDnsChecked() const;
    void setCheckBoxProtoOpenvpnBlockDnsChecked(bool checkBoxProtoOpenvpnBlockDnsChecked);
    QString getLineEditProtoOpenvpnPortText() const;
    void setLineEditProtoOpenvpnPortText(const QString &lineEditProtoOpenvpnPortText);
    bool getCheckBoxProtoOpenvpnTlsAuthChecked() const;
    void setCheckBoxProtoOpenvpnTlsAuthChecked(bool checkBoxProtoOpenvpnTlsAuthChecked);
    bool getRadioButtonSetupWizardHighChecked() const;
    void setRadioButtonSetupWizardHighChecked(bool radioButtonSetupWizardHighChecked);
    bool getRadioButtonSetupWizardLowChecked() const;
    void setRadioButtonSetupWizardLowChecked(bool radioButtonSetupWizardLowChecked);
    bool getCheckBoxSetupWizardVpnModeChecked() const;
    void setCheckBoxSetupWizardVpnModeChecked(bool checkBoxSetupWizardVpnModeChecked);
    QString getIpAddressValidatorRegex() const;
    bool getPushButtonConnectChecked() const;
    void setPushButtonConnectChecked(bool pushButtonConnectChecked);
    QString getLabelSitesAddCustomText() const;
    void setLabelSitesAddCustomText(const QString &labelSitesAddCustomText);
    QObject* getTableViewSitesModel() const;
    void setTableViewSitesModel(QObject *tableViewSitesModel);
    QString getLineEditSitesAddCustomText() const;
    void setLineEditSitesAddCustomText(const QString &lineEditSitesAddCustomText);
    bool getWidgetProtoCloakEnabled() const;
    void setWidgetProtoCloakEnabled(bool widgetProtoCloakEnabled);
    bool getPushButtonProtoCloakSaveVisible() const;
    void setPushButtonProtoCloakSaveVisible(bool pushButtonProtoCloakSaveVisible);
    bool getProgressBarProtoCloakResetVisible() const;
    void setProgressBarProtoCloakResetVisible(bool progressBarProtoCloakResetVisible);
    bool getLineEditProtoCloakPortEnabled() const;
    void setLineEditProtoCloakPortEnabled(bool lineEditProtoCloakPortEnabled);
    bool getWidgetProtoSsEnabled() const;
    void setWidgetProtoSsEnabled(bool widgetProtoSsEnabled);
    bool getPushButtonProtoShadowsocksSaveVisible() const;
    void setPushButtonProtoShadowsocksSaveVisible(bool pushButtonProtoShadowsocksSaveVisible);
    bool getProgressBarProtoShadowsocksResetVisible() const;
    void setProgressBarProtoShadowsocksResetVisible(bool progressBarProtoShadowsocksResetVisible);
    bool getLineEditProtoShadowsocksPortEnabled() const;
    void setLineEditProtoShadowsocksPortEnabled(bool lineEditProtoShadowsocksPortEnabled);
    bool getWidgetProtoOpenvpnEnabled() const;
    void setWidgetProtoOpenvpnEnabled(bool widgetProtoOpenvpnEnabled);
    bool getPushButtonProtoOpenvpnSaveVisible() const;
    void setPushButtonProtoOpenvpnSaveVisible(bool pushButtonProtoOpenvpnSaveVisible);
    bool getProgressBarProtoOpenvpnResetVisible() const;
    void setProgressBarProtoOpenvpnResetVisible(bool progressBarProtoOpenvpnResetVisible);
    bool getRadioButtonProtoOpenvpnUdpEnabled() const;
    void setRadioButtonProtoOpenvpnUdpEnabled(bool radioButtonProtoOpenvpnUdpEnabled);
    bool getRadioButtonProtoOpenvpnTcpEnabled() const;
    void setRadioButtonProtoOpenvpnTcpEnabled(bool radioButtonProtoOpenvpnTcpEnabled);
    bool getRadioButtonProtoOpenvpnTcpChecked() const;
    void setRadioButtonProtoOpenvpnTcpChecked(bool radioButtonProtoOpenvpnTcpChecked);
    bool getLineEditProtoOpenvpnPortEnabled() const;
    void setLineEditProtoOpenvpnPortEnabled(bool lineEditProtoOpenvpnPortEnabled);
    bool getPushButtonProtoOpenvpnContInstallChecked() const;
    void setPushButtonProtoOpenvpnContInstallChecked(bool pushButtonProtoOpenvpnContInstallChecked);
    bool getPushButtonProtoSsOpenvpnContInstallChecked() const;
    void setPushButtonProtoSsOpenvpnContInstallChecked(bool pushButtonProtoSsOpenvpnContInstallChecked);
    bool getPushButtonProtoCloakOpenvpnContInstallChecked() const;
    void setPushButtonProtoCloakOpenvpnContInstallChecked(bool pushButtonProtoCloakOpenvpnContInstallChecked);
    bool getPushButtonProtoWireguardContInstallChecked() const;
    void setPushButtonProtoWireguardContInstallChecked(bool pushButtonProtoWireguardContInstallChecked);
    bool getPushButtonProtoOpenvpnContInstallEnabled() const;
    void setPushButtonProtoOpenvpnContInstallEnabled(bool pushButtonProtoOpenvpnContInstallEnabled);
    bool getPushButtonProtoSsOpenvpnContInstallEnabled() const;
    void setPushButtonProtoSsOpenvpnContInstallEnabled(bool pushButtonProtoSsOpenvpnContInstallEnabled);
    bool getPushButtonProtoCloakOpenvpnContInstallEnabled() const;
    void setPushButtonProtoCloakOpenvpnContInstallEnabled(bool pushButtonProtoCloakOpenvpnContInstallEnabled);
    bool getPushButtonProtoWireguardContInstallEnabled() const;
    void setPushButtonProtoWireguardContInstallEnabled(bool pushButtonProtoWireguardContInstallEnabled);
    bool getPushButtonProtoOpenvpnContDefaultChecked() const;
    void setPushButtonProtoOpenvpnContDefaultChecked(bool pushButtonProtoOpenvpnContDefaultChecked);
    bool getPushButtonProtoSsOpenvpnContDefaultChecked() const;
    void setPushButtonProtoSsOpenvpnContDefaultChecked(bool pushButtonProtoSsOpenvpnContDefaultChecked);
    bool getPushButtonProtoCloakOpenvpnContDefaultChecked() const;
    void setPushButtonProtoCloakOpenvpnContDefaultChecked(bool pushButtonProtoCloakOpenvpnContDefaultChecked);
    bool getPushButtonProtoWireguardContDefaultChecked() const;
    void setPushButtonProtoWireguardContDefaultChecked(bool pushButtonProtoWireguardContDefaultChecked);
    bool getPushButtonProtoOpenvpnContDefaultVisible() const;
    void setPushButtonProtoOpenvpnContDefaultVisible(bool pushButtonProtoOpenvpnContDefaultVisible);
    bool getPushButtonProtoSsOpenvpnContDefaultVisible() const;
    void setPushButtonProtoSsOpenvpnContDefaultVisible(bool pushButtonProtoSsOpenvpnContDefaultVisible);
    bool getPushButtonProtoCloakOpenvpnContDefaultVisible() const;
    void setPushButtonProtoCloakOpenvpnContDefaultVisible(bool pushButtonProtoCloakOpenvpnContDefaultVisible);
    bool getPushButtonProtoWireguardContDefaultVisible() const;
    void setPushButtonProtoWireguardContDefaultVisible(bool pushButtonProtoWireguardContDefaultVisible);
    bool getPushButtonProtoOpenvpnContShareVisible() const;
    void setPushButtonProtoOpenvpnContShareVisible(bool pushButtonProtoOpenvpnContShareVisible);
    bool getPushButtonProtoSsOpenvpnContShareVisible() const;
    void setPushButtonProtoSsOpenvpnContShareVisible(bool pushButtonProtoSsOpenvpnContShareVisible);
    bool getPushButtonProtoCloakOpenvpnContShareVisible() const;
    void setPushButtonProtoCloakOpenvpnContShareVisible(bool pushButtonProtoCloakOpenvpnContShareVisible);
    bool getPushButtonProtoWireguardContShareVisible() const;
    void setPushButtonProtoWireguardContShareVisible(bool pushButtonProtoWireguardContShareVisible);
    bool getFrameOpenvpnSettingsVisible() const;
    void setFrameOpenvpnSettingsVisible(bool frameOpenvpnSettingsVisible);
    bool getFrameOpenvpnSsSettingsVisible() const;
    void setFrameOpenvpnSsSettingsVisible(bool frameOpenvpnSsSettingsVisible);
    bool getFrameOpenvpnSsCloakSettingsVisible() const;
    void setFrameOpenvpnSsCloakSettingsVisible(bool frameOpenvpnSsCloakSettingsVisible);
    bool getProgressBarProtocolsContainerReinstallVisible() const;
    void setProgressBarProtocolsContainerReinstallVisible(bool progressBarProtocolsContainerReinstallVisible);
    QString getLabelSpeedReceivedText() const;
    void setLabelSpeedReceivedText(const QString &labelSpeedReceivedText);
    QString getLabelSpeedSentText() const;
    void setLabelSpeedSentText(const QString &labelSpeedSentText);
    QString getLabelStateText() const;
    void setLabelStateText(const QString &labelStateText);
    bool getPushButtonConnectEnabled() const;
    void setPushButtonConnectEnabled(bool pushButtonConnectEnabled);
    bool getWidgetVpnModeEnabled() const;
    void setWidgetVpnModeEnabled(bool widgetVpnModeEnabled);
    QString getLabelErrorText() const;
    void setLabelErrorText(const QString &labelErrorText);
    bool getPushButtonNewServerConnectEnabled() const;
    void setPushButtonNewServerConnectEnabled(bool pushButtonNewServerConnectEnabled);
    QString getPushButtonNewServerConnectText() const;
    void setPushButtonNewServerConnectText(const QString &pushButtonNewServerConnectText);
    QString getDialogConnectErrorText() const;
    void setDialogConnectErrorText(const QString &dialogConnectErrorText);
    bool getPageServerSettingsEnabled() const;
    void setPageServerSettingsEnabled(bool pageServerSettingsEnabled);
    QString getPushButtonServerSettingsClearText() const;
    void setPushButtonServerSettingsClearText(const QString &pushButtonServerSettingsClearText);
    bool getPageShareAmneziaVisible() const;
    void setPageShareAmneziaVisible(bool pageShareAmneziaVisible);
    bool getPageShareOpenvpnVisible() const;
    void setPageShareOpenvpnVisible(bool pageShareOpenvpnVisible);
    bool getPageShareShadowsocksVisible() const;
    void setPageShareShadowsocksVisible(bool pageShareShadowsocksVisible);
    bool getPageShareCloakVisible() const;
    void setPageShareCloakVisible(bool pageShareCloakVisible);
    bool getPageShareFullAccessVisible() const;
    void setPageShareFullAccessVisible(bool pageShareFullAccessVisible);
    QString getTextEditShareOpenvpnCodeText() const;
    void setTextEditShareOpenvpnCodeText(const QString &textEditShareOpenvpnCodeText);
    bool getPushButtonShareOpenvpnCopyEnabled() const;
    void setPushButtonShareOpenvpnCopyEnabled(bool pushButtonShareOpenvpnCopyEnabled);
    bool getPushButtonShareOpenvpnSaveEnabled() const;
    void setPushButtonShareOpenvpnSaveEnabled(bool pushButtonShareOpenvpnSaveEnabled);
    int getToolBoxShareConnectionCurrentIndex() const;
    void setToolBoxShareConnectionCurrentIndex(int toolBoxShareConnectionCurrentIndex);
    bool getPushButtonShareSsCopyEnabled() const;
    void setPushButtonShareSsCopyEnabled(bool pushButtonShareSsCopyEnabled);
    QString getLineEditShareSsStringText() const;
    void setLineEditShareSsStringText(const QString &lineEditShareSsStringText);
    QString getLabelShareSsQrCodeText() const;
    void setLabelShareSsQrCodeText(const QString &labelShareSsQrCodeText);
    QString getLabelShareSsServerText() const;
    void setLabelShareSsServerText(const QString &labelShareSsServerText);
    QString getLabelShareSsPortText() const;
    void setLabelShareSsPortText(const QString &labelShareSsPortText);
    QString getLabelShareSsMethodText() const;
    void setLabelShareSsMethodText(const QString &labelShareSsMethodText);
    QString getLabelShareSsPasswordText() const;
    void setLabelShareSsPasswordText(const QString &labelShareSsPasswordText);
    QString getPlainTextEditShareCloakText() const;
    void setPlainTextEditShareCloakText(const QString &plainTextEditShareCloakText);
    bool getPushButtonShareCloakCopyEnabled() const;
    void setPushButtonShareCloakCopyEnabled(bool pushButtonShareCloakCopyEnabled);
    QString getTextEditShareFullCodeText() const;
    void setTextEditShareFullCodeText(const QString &textEditShareFullCodeText);
    QString getTextEditShareAmneziaCodeText() const;
    void setTextEditShareAmneziaCodeText(const QString &textEditShareAmneziaCodeText);
    QString getPushButtonShareFullCopyText() const;
    void setPushButtonShareFullCopyText(const QString &pushButtonShareFullCopyText);
    QString getPushButtonShareAmneziaCopyText() const;
    void setPushButtonShareAmneziaCopyText(const QString &pushButtonShareAmneziaCopyText);
    QString getPushButtonShareOpenvpnCopyText() const;
    void setPushButtonShareOpenvpnCopyText(const QString &pushButtonShareOpenvpnCopyText);
    QString getPushButtonShareSsCopyText() const;
    void setPushButtonShareSsCopyText(const QString &pushButtonShareSsCopyText);
    QString getPushButtonShareCloakCopyText() const;
    void setPushButtonShareCloakCopyText(const QString &pushButtonShareCloakCopyText);
    bool getPushButtonShareAmneziaGenerateEnabled() const;
    void setPushButtonShareAmneziaGenerateEnabled(bool pushButtonShareAmneziaGenerateEnabled);
    bool getPushButtonShareAmneziaCopyEnabled() const;
    void setPushButtonShareAmneziaCopyEnabled(bool pushButtonShareAmneziaCopyEnabled);
    QString getPushButtonShareAmneziaGenerateText() const;
    void setPushButtonShareAmneziaGenerateText(const QString &pushButtonShareAmneziaGenerateText);
    bool getPushButtonShareOpenvpnGenerateEnabled() const;
    void setPushButtonShareOpenvpnGenerateEnabled(bool pushButtonShareOpenvpnGenerateEnabled);
    QString getPushButtonShareOpenvpnGenerateText() const;
    void setPushButtonShareOpenvpnGenerateText(const QString &pushButtonShareOpenvpnGenerateText);
    bool getPageNewServerConfiguringEnabled() const;
    void setPageNewServerConfiguringEnabled(bool pageNewServerConfiguringEnabled);
    bool getLabelNewServerConfiguringWaitInfoVisible() const;
    void setLabelNewServerConfiguringWaitInfoVisible(bool labelNewServerConfiguringWaitInfoVisible);
    QString getLabelNewServerConfiguringWaitInfoText() const;
    void setLabelNewServerConfiguringWaitInfoText(const QString &labelNewServerConfiguringWaitInfoText);
    bool getProgressBarNewServerConfiguringVisible() const;
    void setProgressBarNewServerConfiguringVisible(bool progressBarNewServerConfiguringVisible);
    int getProgressBarNewServerConfiguringMaximium() const;
    void setProgressBarNewServerConfiguringMaximium(int progressBarNewServerConfiguringMaximium);
    bool getProgressBarNewServerConfiguringTextVisible() const;
    void setProgressBarNewServerConfiguringTextVisible(bool progressBarNewServerConfiguringTextVisible);
    QString getProgressBarNewServerConfiguringText() const;
    void setProgressBarNewServerConfiguringText(const QString &progressBarNewServerConfiguringText);
    bool getPageServerProtocolsEnabled() const;
    void setPageServerProtocolsEnabled(bool pageServerProtocolsEnabled);
    int getProgressBarProtocolsContainerReinstallValue() const;
    void setProgressBarProtocolsContainerReinstallValue(int progressBarProtocolsContainerReinstallValue);
    int getProgressBarProtocolsContainerReinstallMaximium() const;
    void setProgressBarProtocolsContainerReinstallMaximium(int progressBarProtocolsContainerReinstallMaximium);
    bool getComboBoxProtoOpenvpnCipherEnabled() const;
    void setComboBoxProtoOpenvpnCipherEnabled(bool comboBoxProtoOpenvpnCipherEnabled);
    bool getComboBoxProtoOpenvpnHashEnabled() const;
    void setComboBoxProtoOpenvpnHashEnabled(bool comboBoxProtoOpenvpnHashEnabled);
    bool getPageProtoOpenvpnEnabled() const;
    void setPageProtoOpenvpnEnabled(bool pageProtoOpenvpnEnabled);
    bool getLabelProtoOpenvpnInfoVisible() const;
    void setLabelProtoOpenvpnInfoVisible(bool labelProtoOpenvpnInfoVisible);
    QString getLabelProtoOpenvpnInfoText() const;
    void setLabelProtoOpenvpnInfoText(const QString &labelProtoOpenvpnInfoText);
    int getProgressBarProtoOpenvpnResetValue() const;
    void setProgressBarProtoOpenvpnResetValue(int progressBarProtoOpenvpnResetValue);
    int getProgressBarProtoOpenvpnResetMaximium() const;
    void setProgressBarProtoOpenvpnResetMaximium(int progressBarProtoOpenvpnResetMaximium);
    bool getPageProtoShadowsocksEnabled() const;
    void setPageProtoShadowsocksEnabled(bool pageProtoShadowsocksEnabled);
    bool getLabelProtoShadowsocksInfoVisible() const;
    void setLabelProtoShadowsocksInfoVisible(bool labelProtoShadowsocksInfoVisible);
    QString getLabelProtoShadowsocksInfoText() const;
    void setLabelProtoShadowsocksInfoText(const QString &labelProtoShadowsocksInfoText);
    int getProgressBarProtoShadowsocksResetValue() const;
    void setProgressBarProtoShadowsocksResetValue(int progressBarProtoShadowsocksResetValue);
    int getProgressBarProtoShadowsocksResetMaximium() const;
    void setProgressBarProtoShadowsocksResetMaximium(int progressBarProtoShadowsocksResetMaximium);
    bool getPageProtoCloakEnabled() const;
    void setPageProtoCloakEnabled(bool pageProtoCloakEnabled);
    bool getLabelProtoCloakInfoVisible() const;
    void setLabelProtoCloakInfoVisible(bool labelProtoCloakInfoVisible);
    QString getLabelProtoCloakInfoText() const;
    void setLabelProtoCloakInfoText(const QString &labelProtoCloakInfoText);
    int getProgressBarProtoCloakResetValue() const;
    void setProgressBarProtoCloakResetValue(int progressBarProtoCloakResetValue);
    int getProgressBarProtoCloakResetMaximium() const;
    void setProgressBarProtoCloakResetMaximium(int progressBarProtoCloakResetMaximium);
    QObject* getServerListModel() const;
    QString getPushButtonServerSettingsClearClientCacheText() const;
    void setPushButtonServerSettingsClearClientCacheText(const QString &pushButtonServerSettingsClearClientCacheText);


    Q_INVOKABLE void updateWizardHighPage();
    Q_INVOKABLE void updateNewServerProtocolsPage();
    Q_INVOKABLE void updateStartPage();
    Q_INVOKABLE void updateVpnPage();
    Q_INVOKABLE void updateAppSettingsPage();
    Q_INVOKABLE void updateGeneralSettingPage();
    Q_INVOKABLE void updateServerPage();

    Q_INVOKABLE void onPushButtonNewServerConnect();
    Q_INVOKABLE void onPushButtonNewServerImport();
    Q_INVOKABLE void onPushButtonSetupWizardVpnModeFinishClicked();
    Q_INVOKABLE void onPushButtonSetupWizardLowFinishClicked();
    Q_INVOKABLE void onRadioButtonVpnModeAllSitesToggled(bool checked);
    Q_INVOKABLE void onRadioButtonVpnModeForwardSitesToggled(bool checked);
    Q_INVOKABLE void onRadioButtonVpnModeExceptSitesToggled(bool checked);
    Q_INVOKABLE void onPushButtonAppSettingsOpenLogsChecked();
    Q_INVOKABLE void onCheckBoxAppSettingsAutostartToggled(bool checked);
    Q_INVOKABLE void onCheckBoxAppSettingsAutoconnectToggled(bool checked);
    Q_INVOKABLE void onCheckBoxAppSettingsStartMinimizedToggled(bool checked);
    Q_INVOKABLE void onLineEditNetworkSettingsDns1EditFinished(const QString& text);
    Q_INVOKABLE void onLineEditNetworkSettingsDns2EditFinished(const QString& text);
    Q_INVOKABLE void onPushButtonNetworkSettingsResetdns1Clicked();
    Q_INVOKABLE void onPushButtonNetworkSettingsResetdns2Clicked();
    Q_INVOKABLE void onPushButtonConnectClicked(bool checked);
    Q_INVOKABLE void onPushButtonAddCustomSitesClicked();
    Q_INVOKABLE void onPushButtonSitesDeleteClicked(int row);
    Q_INVOKABLE void onPushButtonSitesImportClicked(const QString &fileName);
    Q_INVOKABLE void onPushButtonShareFullCopyClicked();
    Q_INVOKABLE void onPushButtonShareFullSaveClicked();
    Q_INVOKABLE void onPushButtonShareAmneziaCopyClicked();
    Q_INVOKABLE void onPushButtonShareAmneziaSaveClicked();
    Q_INVOKABLE void onPushButtonShareOpenvpnCopyClicked();
    Q_INVOKABLE void onPushButtonShareSsCopyClicked();
    Q_INVOKABLE void onPushButtonShareCloakCopyClicked();
    Q_INVOKABLE void onPushButtonShareAmneziaGenerateClicked();
    Q_INVOKABLE void onPushButtonShareOpenvpnGenerateClicked();
    Q_INVOKABLE void onPushButtonShareOpenvpnSaveClicked();
    Q_INVOKABLE void onPushButtonGeneralSettingsServerSettingsClicked();
    Q_INVOKABLE void onPushButtonGeneralSettingsShareConnectionClicked();
    Q_INVOKABLE void onPushButtonProtoOpenvpnContOpenvpnConfigClicked();
    Q_INVOKABLE void onPushButtonProtoSsOpenvpnContOpenvpnConfigClicked();
    Q_INVOKABLE void onPushButtonProtoSsOpenvpnContSsConfigClicked();
    Q_INVOKABLE void onPushButtonProtoCloakOpenvpnContOpenvpnConfigClicked();
    Q_INVOKABLE void onPushButtonProtoCloakOpenvpnContSsConfigClicked();
    Q_INVOKABLE void onPushButtonProtoCloakOpenvpnContCloakConfigClicked();
    Q_INVOKABLE void onCheckBoxProtoOpenvpnAutoEncryptionClicked();
    Q_INVOKABLE void onPushButtonProtoOpenvpnSaveClicked();
    Q_INVOKABLE void onPushButtonProtoShadowsocksSaveClicked();
    Q_INVOKABLE void onPushButtonProtoCloakSaveClicked();
    Q_INVOKABLE void onCloseWindow();
    Q_INVOKABLE void onServerListPushbuttonDefaultClicked(int index);
    Q_INVOKABLE void onServerListPushbuttonSettingsClicked(int index);
    Q_INVOKABLE void onPushButtonServerSettingsShareFullClicked();
    Q_INVOKABLE void onPushButtonClearServer();
    Q_INVOKABLE void onPushButtonForgetServer();
    Q_INVOKABLE void onPushButtonServerSettingsClearClientCacheClicked();
    Q_INVOKABLE void onLineEditServerSettingsDescriptionEditingFinished();

signals:
    void frameWireguardSettingsVisibleChanged();
    void frameFireguardVisibleChanged();
    void frameNewServerSettingsParentWireguardVisibleChanged();
    void radioButtonSetupWizardMediumCheckedChanged();
    void lineEditSetupWizardHighWebsiteMaskingTextChanged();
    void progressBarNewServerConfiguringValueChanged();
    void pushButtonNewServerSettingsCloakCheckedChanged();
    void pushButtonNewServerSettingsSsCheckedChanged();
    void pushButtonNewServerSettingsOpenvpnCheckedChanged();
    void lineEditNewServerCloakPortTextChanged();
    void lineEditNewServerCloakSiteTextChanged();
    void lineEditNewServerSsPortTextChanged();
    void comboBoxNewServerSsCipherTextChanged();
    void lineEditNewServerOpenvpnPortTextChanged();
    void comboBoxNewServerOpenvpnProtoTextChanged();
    void pushButtonNewServerConnectKeyCheckedChanged();
    void lineEditStartExistingCodeTextChanged();
    void textEditNewServerSshKeyTextChanged();
    void lineEditNewServerIpTextChanged();
    void lineEditNewServerPasswordTextChanged();
    void lineEditNewServerLoginTextChanged();
    void labelNewServerWaitInfoVisibleChanged();
    void labelNewServerWaitInfoTextChanged();
    void progressBarNewServerConnectionMinimumChanged();
    void progressBarNewServerConnectionMaximumChanged();
    void pushButtonBackFromStartVisibleChanged();
    void pushButtonNewServerConnectVisibleChanged();
    void radioButtonVpnModeAllSitesCheckedChanged();
    void radioButtonVpnModeForwardSitesCheckedChanged();
    void radioButtonVpnModeExceptSitesCheckedChanged();
    void pushButtonVpnAddSiteEnabledChanged();
    void checkBoxAppSettingsAutostartCheckedChanged();
    void checkBoxAppSettingsAutoconnectCheckedChanged();
    void checkBoxAppSettingsStartMinimizedCheckedChanged();
    void lineEditNetworkSettingsDns1TextChanged();
    void lineEditNetworkSettingsDns2TextChanged();
    void labelAppSettingsVersionTextChanged();
    void pushButtonGeneralSettingsShareConnectionEnableChanged();
    void labelServerSettingsWaitInfoVisibleChanged();
    void labelServerSettingsWaitInfoTextChanged();
    void pushButtonServerSettingsClearVisibleChanged();
    void pushButtonServerSettingsClearClientCacheVisibleChanged();
    void pushButtonServerSettingsShareFullVisibleChanged();
    void labelServerSettingsServerTextChanged();
    void lineEditServerSettingsDescriptionTextChanged();
    void labelServerSettingsCurrentVpnProtocolTextChanged();
    void currentPageValueChanged();
    void trayIconUrlChanged();
    void trayActionDisconnectEnabledChanged();
    void trayActionConnectEnabledChanged();
    void checkBoxNewServerCloakCheckedChanged();
    void checkBoxNewServerSsCheckedChanged();
    void checkBoxNewServerOpenvpnCheckedChanged();
    void comboBoxProtoCloakCipherTextChanged();
    void lineEditProtoCloakSiteTextChanged();
    void lineEditProtoCloakPortTextChanged();
    void comboBoxProtoShadowsocksCipherTextChanged();
    void lineEditProtoShadowsocksPortTextChanged();
    void lineEditProtoOpenvpnSubnetTextChanged();
    void radioButtonProtoOpenvpnUdpCheckedChanged();
    void checkBoxProtoOpenvpnAutoEncryptionCheckedChanged();
    void comboBoxProtoOpenvpnCipherTextChanged();
    void comboBoxProtoOpenvpnHashTextChanged();
    void checkBoxProtoOpenvpnBlockDnsCheckedChanged();
    void lineEditProtoOpenvpnPortTextChanged();
    void checkBoxProtoOpenvpnTlsAuthCheckedChanged();
    void radioButtonSetupWizardHighCheckedChanged();
    void radioButtonSetupWizardLowCheckedChanged();
    void checkBoxSetupWizardVpnModeCheckedChanged();
    void pushButtonConnectCheckedChanged();
    void labelSitesAddCustomTextChanged();
    void tableViewSitesModelChanged();
    void lineEditSitesAddCustomTextChanged();
    void widgetProtoCloakEnabledChanged();
    void pushButtonProtoCloakSaveVisibleChanged();
    void progressBarProtoCloakResetVisibleChanged();
    void lineEditProtoCloakPortEnabledChanged();
    void widgetProtoSsEnabledChanged();
    void pushButtonProtoShadowsocksSaveVisibleChanged();
    void progressBarProtoShadowsocksResetVisibleChanged();
    void lineEditProtoShadowsocksPortEnabledChanged();
    void widgetProtoOpenvpnEnabledChanged();
    void pushButtonProtoOpenvpnSaveVisibleChanged();
    void progressBarProtoOpenvpnResetVisibleChanged();
    void radioButtonProtoOpenvpnUdpEnabledChanged();
    void radioButtonProtoOpenvpnTcpEnabledChanged();
    void radioButtonProtoOpenvpnTcpCheckedChanged();
    void lineEditProtoOpenvpnPortEnabledChanged();
    void pushButtonProtoOpenvpnContInstallCheckedChanged();
    void pushButtonProtoSsOpenvpnContInstallCheckedChanged();
    void pushButtonProtoCloakOpenvpnContInstallCheckedChanged();
    void pushButtonProtoWireguardContInstallCheckedChanged();
    void pushButtonProtoOpenvpnContInstallEnabledChanged();
    void pushButtonProtoSsOpenvpnContInstallEnabledChanged();
    void pushButtonProtoCloakOpenvpnContInstallEnabledChanged();
    void pushButtonProtoWireguardContInstallEnabledChanged();
    void pushButtonProtoOpenvpnContDefaultCheckedChanged();
    void pushButtonProtoSsOpenvpnContDefaultCheckedChanged();
    void pushButtonProtoCloakOpenvpnContDefaultCheckedChanged();
    void pushButtonProtoWireguardContDefaultCheckedChanged();
    void pushButtonProtoOpenvpnContDefaultVisibleChanged();
    void pushButtonProtoSsOpenvpnContDefaultVisibleChanged();
    void pushButtonProtoCloakOpenvpnContDefaultVisibleChanged();
    void pushButtonProtoWireguardContDefaultVisibleChanged();
    void pushButtonProtoOpenvpnContShareVisibleChanged();
    void pushButtonProtoSsOpenvpnContShareVisibleChanged();
    void pushButtonProtoCloakOpenvpnContShareVisibleChanged();
    void pushButtonProtoWireguardContShareVisibleChanged();
    void frameOpenvpnSettingsVisibleChanged();
    void frameOpenvpnSsSettingsVisibleChanged();
    void frameOpenvpnSsCloakSettingsVisibleChanged();
    void progressBarProtocolsContainerReinstallVisibleChanged();
    void labelSpeedReceivedTextChanged();
    void labelSpeedSentTextChanged();
    void labelStateTextChanged();
    void pushButtonConnectEnabledChanged();
    void widgetVpnModeEnabledChanged();
    void labelErrorTextChanged();
    void pushButtonNewServerConnectEnabledChanged();
    void pushButtonNewServerConnectTextChanged();
    void dialogConnectErrorTextChanged();
    void pageServerSettingsEnabledChanged();
    void pushButtonServerSettingsClearTextChanged();
    void pageShareAmneziaVisibleChanged();
    void pageShareOpenvpnVisibleChanged();
    void pageShareShadowsocksVisibleChanged();
    void pageShareCloakVisibleChanged();
    void pageShareFullAccessVisibleChanged();
    void textEditShareOpenvpnCodeTextChanged();
    void pushButtonShareOpenvpnCopyEnabledChanged();
    void pushButtonShareOpenvpnSaveEnabledChanged();
    void toolBoxShareConnectionCurrentIndexChanged();
    void pushButtonShareSsCopyEnabledChanged();
    void lineEditShareSsStringTextChanged();
    void labelShareSsQrCodeTextChanged();
    void labelShareSsServerTextChanged();
    void labelShareSsPortTextChanged();
    void labelShareSsMethodTextChanged();
    void labelShareSsPasswordTextChanged();
    void plainTextEditShareCloakTextChanged();
    void pushButtonShareCloakCopyEnabledChanged();
    void textEditShareFullCodeTextChanged();
    void textEditShareAmneziaCodeTextChanged();
    void pushButtonShareFullCopyTextChanged();
    void pushButtonShareAmneziaCopyTextChanged();
    void pushButtonShareOpenvpnCopyTextChanged();
    void pushButtonShareSsCopyTextChanged();
    void pushButtonShareCloakCopyTextChanged();
    void pushButtonShareAmneziaGenerateEnabledChanged();
    void pushButtonShareAmneziaCopyEnabledChanged();
    void pushButtonShareAmneziaGenerateTextChanged();
    void pushButtonShareOpenvpnGenerateEnabledChanged();
    void pushButtonShareOpenvpnGenerateTextChanged();
    void pageNewServerConfiguringEnabledChanged();
    void labelNewServerConfiguringWaitInfoVisibleChanged();
    void labelNewServerConfiguringWaitInfoTextChanged();
    void progressBarNewServerConfiguringVisibleChanged();
    void progressBarNewServerConfiguringMaximiumChanged();
    void progressBarNewServerConfiguringTextVisibleChanged();
    void progressBarNewServerConfiguringTextChanged();
    void pageServerProtocolsEnabledChanged();
    void progressBarProtocolsContainerReinstallValueChanged();
    void progressBarProtocolsContainerReinstallMaximiumChanged();
    void comboBoxProtoOpenvpnCipherEnabledChanged();
    void comboBoxProtoOpenvpnHashEnabledChanged();
    void pageProtoOpenvpnEnabledChanged();
    void labelProtoOpenvpnInfoVisibleChanged();
    void labelProtoOpenvpnInfoTextChanged();
    void progressBarProtoOpenvpnResetValueChanged();
    void progressBarProtoOpenvpnResetMaximiumChanged();
    void pageProtoShadowsocksEnabledChanged();
    void labelProtoShadowsocksInfoVisibleChanged();
    void labelProtoShadowsocksInfoTextChanged();
    void progressBarProtoShadowsocksResetValueChanged();
    void progressBarProtoShadowsocksResetMaximiumChanged();
    void pageProtoCloakEnabledChanged();
    void labelProtoCloakInfoVisibleChanged();
    void labelProtoCloakInfoTextChanged();
    void progressBarProtoCloakResetValueChanged();
    void progressBarProtoCloakResetMaximiumChanged();
    void pushButtonServerSettingsClearClientCacheTextChanged();

    void goToPage(int page, bool reset = true, bool slide = true);
    void closePage();
    void setStartPage(int page, bool slide = true);
    void pushButtonNewServerConnectConfigureClicked();
    void showPublicKeyWarning();
    void showConnectErrorDialog();
    void show();
    void hide();
    void pushButtonProtoOpenvpnContDefaultClicked(bool checked);
    void pushButtonProtoSsOpenvpnContDefaultClicked(bool checked);
    void pushButtonProtoCloakOpenvpnContDefaultClicked(bool checked);
    void pushButtonProtoWireguardContDefaultClicked(bool checked);
    void pushButtonProtoOpenvpnContInstallClicked(bool checked);
    void pushButtonProtoSsOpenvpnContInstallClicked(bool checked);
    void pushButtonProtoCloakOpenvpnContInstallClicked(bool checked);
    void pushButtonProtoWireguardContInstallClicked(bool checked);
    void pushButtonProtoOpenvpnContShareClicked(bool checked);
    void pushButtonProtoSsOpenvpnContShareClicked(bool checked);
    void pushButtonProtoCloakOpenvpnContShareClicked(bool checked);
    void pushButtonProtoWireguardContShareClicked(bool checked);

private:
    bool m_frameWireguardSettingsVisible;
    bool m_frameFireguardVisible;
    bool m_frameNewServerSettingsParentWireguardVisible;
    bool m_radioButtonSetupWizardMediumChecked;
    QString m_lineEditSetupWizardHighWebsiteMaskingText;
    double m_progressBarNewServerConfiguringValue;
    bool m_pushButtonNewServerSettingsCloakChecked;
    bool m_pushButtonNewServerSettingsSsChecked;
    bool m_pushButtonNewServerSettingsOpenvpnChecked;
    QString m_lineEditNewServerCloakPortText;
    QString m_lineEditNewServerCloakSiteText;
    QString m_lineEditNewServerSsPortText;
    QString m_comboBoxNewServerSsCipherText;
    QString m_lineEditNewServerOpenvpnPortText;
    QString m_comboBoxNewServerOpenvpnProtoText;
    bool m_pushButtonNewServerConnectKeyChecked;
    QString m_lineEditStartExistingCodeText;
    QString m_textEditNewServerSshKeyText;
    QString m_lineEditNewServerIpText;
    QString m_lineEditNewServerPasswordText;
    QString m_lineEditNewServerLoginText;
    bool m_labelNewServerWaitInfoVisible;
    QString m_labelNewServerWaitInfoText;
    double m_progressBarNewServerConnectionMinimum;
    double m_progressBarNewServerConnectionMaximum;
    bool m_pushButtonBackFromStartVisible;
    bool m_pushButtonNewServerConnectVisible;
    bool m_radioButtonVpnModeAllSitesChecked;
    bool m_radioButtonVpnModeForwardSitesChecked;
    bool m_radioButtonVpnModeExceptSitesChecked;
    bool m_pushButtonVpnAddSiteEnabled;
    bool m_checkBoxAppSettingsAutostartChecked;
    bool m_checkBoxAppSettingsAutoconnectChecked;
    bool m_checkBoxAppSettingsStartMinimizedChecked;
    QString m_lineEditNetworkSettingsDns1Text;
    QString m_lineEditNetworkSettingsDns2Text;
    QString m_labelAppSettingsVersionText;
    bool m_pushButtonGeneralSettingsShareConnectionEnable;
    bool m_labelServerSettingsWaitInfoVisible;
    QString m_labelServerSettingsWaitInfoText;
    bool m_pushButtonServerSettingsClearVisible;
    bool m_pushButtonServerSettingsClearClientCacheVisible;
    bool m_pushButtonServerSettingsShareFullVisible;
    QString m_labelServerSettingsServerText;
    QString m_lineEditServerSettingsDescriptionText;
    QString m_labelServerSettingsCurrentVpnProtocolText;
    int m_currentPageValue;
    QString m_trayIconUrl;
    bool m_trayActionDisconnectEnabled;
    bool m_trayActionConnectEnabled;
    bool m_checkBoxNewServerCloakChecked;
    bool m_checkBoxNewServerSsChecked;
    bool m_checkBoxNewServerOpenvpnChecked;
    QString m_comboBoxProtoCloakCipherText;
    QString m_lineEditProtoCloakSiteText;
    QString m_lineEditProtoCloakPortText;
    QString m_comboBoxProtoShadowsocksCipherText;
    QString m_lineEditProtoShadowsocksPortText;
    QString m_lineEditProtoOpenvpnSubnetText;
    bool m_radioButtonProtoOpenvpnUdpChecked;
    bool m_checkBoxProtoOpenvpnAutoEncryptionChecked;
    QString m_comboBoxProtoOpenvpnCipherText;
    QString m_comboBoxProtoOpenvpnHashText;
    bool m_checkBoxProtoOpenvpnBlockDnsChecked;
    QString m_lineEditProtoOpenvpnPortText;
    bool m_checkBoxProtoOpenvpnTlsAuthChecked;
    bool m_radioButtonSetupWizardHighChecked;
    bool m_radioButtonSetupWizardLowChecked;
    bool m_checkBoxSetupWizardVpnModeChecked;
    QString m_ipAddressValidatorRegex;
    bool m_pushButtonConnectChecked;
    QString m_labelSitesAddCustomText;
    QObject* m_tableViewSitesModel;
    QString m_lineEditSitesAddCustomText;
    bool m_widgetProtoCloakEnabled;
    bool m_pushButtonProtoCloakSaveVisible;
    bool m_progressBarProtoCloakResetVisible;
    bool m_lineEditProtoCloakPortEnabled;
    bool m_widgetProtoSsEnabled;
    bool m_pushButtonProtoShadowsocksSaveVisible;
    bool m_progressBarProtoShadowsocksResetVisible;
    bool m_lineEditProtoShadowsocksPortEnabled;
    bool m_widgetProtoOpenvpnEnabled;
    bool m_pushButtonProtoOpenvpnSaveVisible;
    bool m_progressBarProtoOpenvpnResetVisible;
    bool m_radioButtonProtoOpenvpnUdpEnabled;
    bool m_radioButtonProtoOpenvpnTcpEnabled;
    bool m_radioButtonProtoOpenvpnTcpChecked;
    bool m_lineEditProtoOpenvpnPortEnabled;
    bool m_pushButtonProtoOpenvpnContInstallChecked;
    bool m_pushButtonProtoSsOpenvpnContInstallChecked;
    bool m_pushButtonProtoCloakOpenvpnContInstallChecked;
    bool m_pushButtonProtoWireguardContInstallChecked;
    bool m_pushButtonProtoOpenvpnContInstallEnabled;
    bool m_pushButtonProtoSsOpenvpnContInstallEnabled;
    bool m_pushButtonProtoCloakOpenvpnContInstallEnabled;
    bool m_pushButtonProtoWireguardContInstallEnabled;
    bool m_pushButtonProtoOpenvpnContDefaultChecked;
    bool m_pushButtonProtoSsOpenvpnContDefaultChecked;
    bool m_pushButtonProtoCloakOpenvpnContDefaultChecked;
    bool m_pushButtonProtoWireguardContDefaultChecked;
    bool m_pushButtonProtoOpenvpnContDefaultVisible;
    bool m_pushButtonProtoSsOpenvpnContDefaultVisible;
    bool m_pushButtonProtoCloakOpenvpnContDefaultVisible;
    bool m_pushButtonProtoWireguardContDefaultVisible;
    bool m_pushButtonProtoOpenvpnContShareVisible;
    bool m_pushButtonProtoSsOpenvpnContShareVisible;
    bool m_pushButtonProtoCloakOpenvpnContShareVisible;
    bool m_pushButtonProtoWireguardContShareVisible;
    bool m_frameOpenvpnSettingsVisible;
    bool m_frameOpenvpnSsSettingsVisible;
    bool m_frameOpenvpnSsCloakSettingsVisible;
    bool m_progressBarProtocolsContainerReinstallVisible;
    QString m_labelSpeedReceivedText;
    QString m_labelSpeedSentText;
    QString m_labelStateText;
    bool m_pushButtonConnectEnabled;
    bool m_widgetVpnModeEnabled;
    QString m_labelErrorText;
    bool m_pushButtonNewServerConnectEnabled;
    QString m_pushButtonNewServerConnectText;
    QString m_dialogConnectErrorText;
    bool m_pageServerSettingsEnabled;
    QString m_pushButtonServerSettingsClearText;
    bool m_pageShareAmneziaVisible;
    bool m_pageShareOpenvpnVisible;
    bool m_pageShareShadowsocksVisible;
    bool m_pageShareCloakVisible;
    bool m_pageShareFullAccessVisible;
    QString m_textEditShareOpenvpnCodeText;
    bool m_pushButtonShareOpenvpnCopyEnabled;
    bool m_pushButtonShareOpenvpnSaveEnabled;
    int m_toolBoxShareConnectionCurrentIndex;
    bool m_pushButtonShareSsCopyEnabled;
    QString m_lineEditShareSsStringText;
    QString m_labelShareSsQrCodeText;
    QString m_labelShareSsServerText;
    QString m_labelShareSsPortText;
    QString m_labelShareSsMethodText;
    QString m_labelShareSsPasswordText;
    QString m_plainTextEditShareCloakText;
    bool m_pushButtonShareCloakCopyEnabled;
    QString m_textEditShareFullCodeText;
    QString m_textEditShareAmneziaCodeText;
    QString m_pushButtonShareFullCopyText;
    QString m_pushButtonShareAmneziaCopyText;
    QString m_pushButtonShareOpenvpnCopyText;
    QString m_pushButtonShareSsCopyText;
    QString m_pushButtonShareCloakCopyText;
    bool m_pushButtonShareAmneziaGenerateEnabled;
    bool m_pushButtonShareAmneziaCopyEnabled;
    QString m_pushButtonShareAmneziaGenerateText;
    bool m_pushButtonShareOpenvpnGenerateEnabled;
    QString m_pushButtonShareOpenvpnGenerateText;
    bool m_pageNewServerConfiguringEnabled;
    bool m_labelNewServerConfiguringWaitInfoVisible;
    QString m_labelNewServerConfiguringWaitInfoText;
    bool m_progressBarNewServerConfiguringVisible;
    int m_progressBarNewServerConfiguringMaximium;
    bool m_progressBarNewServerConfiguringTextVisible;
    QString m_progressBarNewServerConfiguringText;
    bool m_pageServerProtocolsEnabled;
    int m_progressBarProtocolsContainerReinstallValue;
    int m_progressBarProtocolsContainerReinstallMaximium;
    bool m_comboBoxProtoOpenvpnCipherEnabled;
    bool m_comboBoxProtoOpenvpnHashEnabled;
    bool m_pageProtoOpenvpnEnabled;
    bool m_labelProtoOpenvpnInfoVisible;
    QString m_labelProtoOpenvpnInfoText;
    int m_progressBarProtoOpenvpnResetValue;
    int m_progressBarProtoOpenvpnResetMaximium;
    bool m_pageProtoShadowsocksEnabled;
    bool m_labelProtoShadowsocksInfoVisible;
    QString m_labelProtoShadowsocksInfoText;
    int m_progressBarProtoShadowsocksResetValue;
    int m_progressBarProtoShadowsocksResetMaximium;
    bool m_pageProtoCloakEnabled;
    bool m_labelProtoCloakInfoVisible;
    QString m_labelProtoCloakInfoText;
    int m_progressBarProtoCloakResetValue;
    int m_progressBarProtoCloakResetMaximium;
    ServersModel* m_serverListModel;
    QString m_pushButtonServerSettingsClearClientCacheText;

private slots:
    void onBytesChanged(quint64 receivedBytes, quint64 sentBytes);
    void onConnectionStateChanged(VpnProtocol::ConnectionState state);
    void onVpnProtocolError(amnezia::ErrorCode errorCode);

    void installServer(const QMap<DockerContainer, QJsonObject> &containers);
    void setTrayState(VpnProtocol::ConnectionState state);
    void onConnect();
    void onConnectWorker(int serverIndex, const ServerCredentials &credentials, DockerContainer container, const QJsonObject &containerConfig);
    void onDisconnect();


private:
    PageEnumNS::Page currentPage();
    struct ProgressFunc {
        std::function<void(bool)> setVisibleFunc;
        std::function<void(int)> setValueFunc;
        std::function<int(void)> getValueFunc;
        std::function<int(void)> getMaximiumFunc;
        std::function<void(bool)> setTextVisibleFunc;
        std::function<void(const QString&)> setTextFunc;
    };
    struct PageFunc {
        std::function<void(bool)> setEnabledFunc;
    };
    struct ButtonFunc {
        std::function<void(bool)> setVisibleFunc;
    };
    struct LabelFunc {
        std::function<void(bool)> setVisibleFunc;
        std::function<void(const QString&)> setTextFunc;
    };

    bool installContainers(ServerCredentials credentials,
                           const QMap<DockerContainer, QJsonObject> &containers,
                           const PageFunc& page,
                           const ProgressFunc& progress,
                           const ButtonFunc& button,
                           const LabelFunc& info);

    ErrorCode doInstallAction(const std::function<ErrorCode()> &action,
                              const PageFunc& page,
                              const ProgressFunc& progress,
                              const ButtonFunc& button,
                              const LabelFunc& info);

    void setupTray();
    void setTrayIcon(const QString &iconPath);

    void setupNewServerConnections();
    void setupSitesPageConnections();
    void setupProtocolsPageConnections();

    void updateSitesPage();
    void updateServersListPage();
    void updateProtocolsPage();
    void updateOpenVpnPage(const QJsonObject &openvpnConfig, DockerContainer container, bool haveAuthData);
    void updateShadowSocksPage(const QJsonObject &ssConfig, DockerContainer container, bool haveAuthData);
    void updateCloakPage(const QJsonObject &ckConfig, DockerContainer container, bool haveAuthData);

    void updateSharingPage(int serverIndex, const ServerCredentials &credentials,
                           DockerContainer container);
    void updateQRCodeImage(const QString &text, const std::function<void(const QString&)>& setLabelFunc);

    QJsonObject getOpenVpnConfigFromPage(QJsonObject oldConfig);
    QJsonObject getShadowSocksConfigFromPage(QJsonObject oldConfig);
    QJsonObject getCloakConfigFromPage(QJsonObject oldConfig);

    QMap<DockerContainer, QJsonObject> getInstallConfigsFromProtocolsPage() const;
    QMap<DockerContainer, QJsonObject> getInstallConfigsFromWizardPage() const;

private:
    VpnConnection* m_vpnConnection;
    Settings m_settings;

    QMap<Settings::RouteMode, SitesModel *> sitesModels;

    //    QRegExpValidator m_ipAddressValidator;
    //    QRegExpValidator m_ipAddressPortValidator;
    //    QRegExpValidator m_ipNetwok24Validator;
    //    QRegExpValidator m_ipPortValidator;

    CQR_Encode m_qrEncode;

    //    QPoint offset;
    //    bool needToHideCustomTitlebar = false;

    //    void keyPressEvent(QKeyEvent* event) override;
    //    void showEvent(QShowEvent *event) override;
    //    void hideEvent(QHideEvent *event) override;

    const QString ConnectedTrayIconName = "active.png";
    const QString DisconnectedTrayIconName = "default.png";
    const QString ErrorTrayIconName = "error.png";


    //    QStack<Page> pagesStack;
    int selectedServerIndex = -1; // server index to use when proto settings page opened
    DockerContainer selectedDockerContainer; // same
    ServerCredentials installCredentials; // used to save cred between pages new_server and new_server_protocols and wizard
};
#endif // UILOGIC_H
