set(QTSERVICE_LIBNAME QtSolutions_Service-head)
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    if(APPLE)
        set(QTSERVICE_LIBNAME ${QTSERVICE_LIBNAME}_debug)
    elseif(WIN32)
        set(QTSERVICE_LIBNAME ${QTSERVICE_LIBNAME}_d)
    endif()
endif()

set(QTSERVICE_LIBDIR ${CMAKE_CURRENT_LIST_DIR}/lib)

if(UNIX)
    if(qtservice-uselib)
        if(NOT qtservice-buildlib)
            set(CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_RPATH} ${QTSERVICE_LIBDIR})
        endif()
    endif()
endif()
