/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class ClientAPI_ExternalPKICertRequest extends ClientAPI_ExternalPKIRequestBase {
  private transient long swigCPtr;

  protected ClientAPI_ExternalPKICertRequest(long cPtr, boolean cMemoryOwn) {
    super(ovpncliJNI.ClientAPI_ExternalPKICertRequest_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientAPI_ExternalPKICertRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ClientAPI_ExternalPKICertRequest obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_ClientAPI_ExternalPKICertRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setCert(String value) {
    ovpncliJNI.ClientAPI_ExternalPKICertRequest_cert_set(swigCPtr, this, value);
  }

  public String getCert() {
    return ovpncliJNI.ClientAPI_ExternalPKICertRequest_cert_get(swigCPtr, this);
  }

  public void setSupportingChain(String value) {
    ovpncliJNI.ClientAPI_ExternalPKICertRequest_supportingChain_set(swigCPtr, this, value);
  }

  public String getSupportingChain() {
    return ovpncliJNI.ClientAPI_ExternalPKICertRequest_supportingChain_get(swigCPtr, this);
  }

  public ClientAPI_ExternalPKICertRequest() {
    this(ovpncliJNI.new_ClientAPI_ExternalPKICertRequest(), true);
  }

}
