/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class ClientAPI_EvalConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientAPI_EvalConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientAPI_EvalConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ClientAPI_EvalConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_ClientAPI_EvalConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setError(boolean value) {
    ovpncliJNI.ClientAPI_EvalConfig_error_set(swigCPtr, this, value);
  }

  public boolean getError() {
    return ovpncliJNI.ClientAPI_EvalConfig_error_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return ovpncliJNI.ClientAPI_EvalConfig_message_get(swigCPtr, this);
  }

  public void setUserlockedUsername(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_userlockedUsername_set(swigCPtr, this, value);
  }

  public String getUserlockedUsername() {
    return ovpncliJNI.ClientAPI_EvalConfig_userlockedUsername_get(swigCPtr, this);
  }

  public void setProfileName(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_profileName_set(swigCPtr, this, value);
  }

  public String getProfileName() {
    return ovpncliJNI.ClientAPI_EvalConfig_profileName_get(swigCPtr, this);
  }

  public void setFriendlyName(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_friendlyName_set(swigCPtr, this, value);
  }

  public String getFriendlyName() {
    return ovpncliJNI.ClientAPI_EvalConfig_friendlyName_get(swigCPtr, this);
  }

  public void setAutologin(boolean value) {
    ovpncliJNI.ClientAPI_EvalConfig_autologin_set(swigCPtr, this, value);
  }

  public boolean getAutologin() {
    return ovpncliJNI.ClientAPI_EvalConfig_autologin_get(swigCPtr, this);
  }

  public void setExternalPki(boolean value) {
    ovpncliJNI.ClientAPI_EvalConfig_externalPki_set(swigCPtr, this, value);
  }

  public boolean getExternalPki() {
    return ovpncliJNI.ClientAPI_EvalConfig_externalPki_get(swigCPtr, this);
  }

  public void setStaticChallenge(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_staticChallenge_set(swigCPtr, this, value);
  }

  public String getStaticChallenge() {
    return ovpncliJNI.ClientAPI_EvalConfig_staticChallenge_get(swigCPtr, this);
  }

  public void setStaticChallengeEcho(boolean value) {
    ovpncliJNI.ClientAPI_EvalConfig_staticChallengeEcho_set(swigCPtr, this, value);
  }

  public boolean getStaticChallengeEcho() {
    return ovpncliJNI.ClientAPI_EvalConfig_staticChallengeEcho_get(swigCPtr, this);
  }

  public void setPrivateKeyPasswordRequired(boolean value) {
    ovpncliJNI.ClientAPI_EvalConfig_privateKeyPasswordRequired_set(swigCPtr, this, value);
  }

  public boolean getPrivateKeyPasswordRequired() {
    return ovpncliJNI.ClientAPI_EvalConfig_privateKeyPasswordRequired_get(swigCPtr, this);
  }

  public void setAllowPasswordSave(boolean value) {
    ovpncliJNI.ClientAPI_EvalConfig_allowPasswordSave_set(swigCPtr, this, value);
  }

  public boolean getAllowPasswordSave() {
    return ovpncliJNI.ClientAPI_EvalConfig_allowPasswordSave_get(swigCPtr, this);
  }

  public void setRemoteHost(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_remoteHost_set(swigCPtr, this, value);
  }

  public String getRemoteHost() {
    return ovpncliJNI.ClientAPI_EvalConfig_remoteHost_get(swigCPtr, this);
  }

  public void setRemotePort(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_remotePort_set(swigCPtr, this, value);
  }

  public String getRemotePort() {
    return ovpncliJNI.ClientAPI_EvalConfig_remotePort_get(swigCPtr, this);
  }

  public void setRemoteProto(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_remoteProto_set(swigCPtr, this, value);
  }

  public String getRemoteProto() {
    return ovpncliJNI.ClientAPI_EvalConfig_remoteProto_get(swigCPtr, this);
  }

  public void setServerList(ClientAPI_ServerEntryVector value) {
    ovpncliJNI.ClientAPI_EvalConfig_serverList_set(swigCPtr, this, ClientAPI_ServerEntryVector.getCPtr(value), value);
  }

  public ClientAPI_ServerEntryVector getServerList() {
    long cPtr = ovpncliJNI.ClientAPI_EvalConfig_serverList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ClientAPI_ServerEntryVector(cPtr, false);
  }

  public void setWindowsDriver(String value) {
    ovpncliJNI.ClientAPI_EvalConfig_windowsDriver_set(swigCPtr, this, value);
  }

  public String getWindowsDriver() {
    return ovpncliJNI.ClientAPI_EvalConfig_windowsDriver_get(swigCPtr, this);
  }

  public ClientAPI_EvalConfig() {
    this(ovpncliJNI.new_ClientAPI_EvalConfig(), true);
  }

}
