// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAutoRenew() {
  return window['go']['main']['App']['CancelAutoRenew']();
}

export function CheckPayment(arg1) {
  return window['go']['main']['App']['CheckPayment'](arg1);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnableAutoRenew() {
  return window['go']['main']['App']['EnableAutoRenew']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetPaymentHistory() {
  return window['go']['main']['App']['GetPaymentHistory']();
}

export function GetPaymentMethod() {
  return window['go']['main']['App']['GetPaymentMethod']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSubscription() {
  return window['go']['main']['App']['GetSubscription']();
}

export function InitPayment(arg1) {
  return window['go']['main']['App']['InitPayment'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SavePaymentMethod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePaymentMethod'](arg1, arg2, arg3);
}
