// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAutoRenew():Promise<void>;

export function CheckPayment(arg1:string):Promise<string>;

export function Connect(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function EnableAutoRenew():Promise<void>;

export function GetCurrentUser():Promise<main.User>;

export function GetPaymentHistory():Promise<Array<main.PaymentRecord>>;

export function GetPaymentMethod():Promise<main.PaymentMethod>;

export function GetServers():Promise<Array<main.Server>>;

export function GetSubscription():Promise<main.Subscription>;

export function InitPayment(arg1:string):Promise<main.APIPaymentResponse>;

export function IsConnected():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.User>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<main.User>;

export function SavePaymentMethod(arg1:string,arg2:string,arg3:string):Promise<void>;
