/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class ClientAPI_RemoteOverride {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientAPI_RemoteOverride(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientAPI_RemoteOverride obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_ClientAPI_RemoteOverride(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHost(String value) {
    ovpncliJNI.ClientAPI_RemoteOverride_host_set(swigCPtr, this, value);
  }

  public String getHost() {
    return ovpncliJNI.ClientAPI_RemoteOverride_host_get(swigCPtr, this);
  }

  public void setIp(String value) {
    ovpncliJNI.ClientAPI_RemoteOverride_ip_set(swigCPtr, this, value);
  }

  public String getIp() {
    return ovpncliJNI.ClientAPI_RemoteOverride_ip_get(swigCPtr, this);
  }

  public void setPort(String value) {
    ovpncliJNI.ClientAPI_RemoteOverride_port_set(swigCPtr, this, value);
  }

  public String getPort() {
    return ovpncliJNI.ClientAPI_RemoteOverride_port_get(swigCPtr, this);
  }

  public void setProto(String value) {
    ovpncliJNI.ClientAPI_RemoteOverride_proto_set(swigCPtr, this, value);
  }

  public String getProto() {
    return ovpncliJNI.ClientAPI_RemoteOverride_proto_get(swigCPtr, this);
  }

  public void setError(String value) {
    ovpncliJNI.ClientAPI_RemoteOverride_error_set(swigCPtr, this, value);
  }

  public String getError() {
    return ovpncliJNI.ClientAPI_RemoteOverride_error_get(swigCPtr, this);
  }

  public ClientAPI_RemoteOverride() {
    this(ovpncliJNI.new_ClientAPI_RemoteOverride(), true);
  }

}
