/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class ClientAPI_KeyValue {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientAPI_KeyValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientAPI_KeyValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_ClientAPI_KeyValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ClientAPI_KeyValue() {
    this(ovpncliJNI.new_ClientAPI_KeyValue__SWIG_0(), true);
  }

  public ClientAPI_KeyValue(String key_arg, String value_arg) {
    this(ovpncliJNI.new_ClientAPI_KeyValue__SWIG_1(key_arg, value_arg), true);
  }

  public void setKey(String value) {
    ovpncliJNI.ClientAPI_KeyValue_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return ovpncliJNI.ClientAPI_KeyValue_key_get(swigCPtr, this);
  }

  public void setValue(String value) {
    ovpncliJNI.ClientAPI_KeyValue_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return ovpncliJNI.ClientAPI_KeyValue_value_get(swigCPtr, this);
  }

}
