if(WIN32)
    if (SIGNTOOL_SUBJECT_NAME)
        include(${CMAKE_CURRENT_LIST_DIR}/util/signtool.cmake)
        foreach(PACKAGE_FILE IN LISTS CPACK_PACKAGE_FILES)
            signtool_sign_files("${PACKAGE_FILE}" "${SIGNTOOL_SUBJECT_NAME}")
        endforeach()
    endif()
endif()

if(APPLE)
    if(CODESIGN_SIGNATURE)
        include(${CMAKE_CURRENT_LIST_DIR}/util/codesign.cmake)
        codesign_sign_files("${CPACK_PACKAGE_FILES}" "${CODESIGN_SIGNATURE}" "${CODESIGN_KEYCHAIN}")
    endif()

    if(NOTARYTOOL_EMAIL AND NOTARYTOOL_TEAM_ID AND NOTARYTOOL_PASSWORD)
        include(${CMAKE_CURRENT_LIST_DIR}/util/notarytool.cmake)
        foreach(file IN LISTS CPACK_PACKAGE_FILES)
            notarize_and_staple_file("${file}" "${NOTARYTOOL_EMAIL}" "${NOTARYTOOL_TEAM_ID}" "${NOTARYTOOL_PASSWORD}")
        endforeach()
    endif()
endif()
